### ISSUE TITLE
[umbrella] OverrideRules of OverridePolicy

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1113]
**What would you like to be added**:
We've introduced [OverrideRules ][1] to `OverridePolicy` and `ClusterOverridePolicy` by #1109, but haven't implement it yet.

This issue splits the task into several iterated items:
- [x] karmada-controller-manager: Implementes the new  `OverrideRules` (Make sure backward compatibility: the old OverridePolicy still works) (#1114 by @iawia002 )
- [x] karmada-webhook: Valitating webhook(It's not allowed if `OverrideRules` and (`Overriders` or `TargetCluster`) co-exist ) (#1124, by @lonelyCZ )
- [x] karmada-webhook: Validating ClusterOverridePolicy((It's not allowed if `OverrideRules` and (`Overriders` or `TargetCluster`) co-exist ) ) (#1129, @lonelyCZ )
- [x] karmadactl: Update [webhook default configurations][5]. (#1134, @lonelyCZ )
- [x] docs: update [example artifacts][4] accordingly (#1114 by @iawia002 )
- [ ] API: mark [TargetCluster][2] and [Overriders][3] deprecated (@RainbowMango )
- [x] E2E: Add a test for it (#1126, @jameszhangyukun )

**Why is this needed**:

[1]: https://github.com/karmada-io/karmada/blob/5e6d213012bcf2076a7277979920b0a4a7172055/pkg/apis/policy/v1alpha1/override_types.go#L30
[2]: https://github.com/karmada-io/karmada/blob/5e6d213012bcf2076a7277979920b0a4a7172055/pkg/apis/policy/v1alpha1/override_types.go#L36
[3]: https://github.com/karmada-io/karmada/blob/5e6d213012bcf2076a7277979920b0a4a7172055/pkg/apis/policy/v1alpha1/override_types.go#L40
[4]: https://github.com/karmada-io/karmada/tree/master/artifacts/example
[5]: https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

**Comment by lonelyCZ** [comment]
I'm interested in `karmada-webhook: Valitating webhook(It's not allowed if OverrideRules and (Overriders or TargetCluster) co-exist )`, I would like to take it.

**Comment by jameszhangyukun** [comment]
I'm interested in ` E2E: Add a test for it` I want to  take it

**Comment by RainbowMango** [comment]
/assign @lonelyCZ @jameszhangyukun  
Thank you guys.

**Comment by iawia002** [comment]
` docs: update example artifacts accordingly` I can do this together with the first topic.

**Comment by RainbowMango** [comment]
Thanks.

**Comment by lonelyCZ** [comment]
Hi, @RainbowMango 
Whether to set this field to a point? It doesn't compare with `nil`.
https://github.com/karmada-io/karmada/blob/5e6d213012bcf2076a7277979920b0a4a7172055/pkg/apis/policy/v1alpha1/override_types.go#L40

 And if not to set, it still exist.
```yaml
spec:
  overriders: {}
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx
```

**Comment by RainbowMango** [comment]
> Whether to set this field to a point? It doesn't compare with nil.

No, It will introduce incompatible change.

If all of the fields are empty(e.g. `len(Overrides.Plaintext) == 0`), we can think it's emtpy.

**Comment by RainbowMango** [comment]
@jameszhangyukun For the E2E test, I think @iawia002 gives an example at #1114 :)

**Comment by lonelyCZ** [comment]
Hi, @RainbowMango 
Do I need to edit this file manually？
https://github.com/karmada-io/karmada/blob/7dcb197f9e62be4a361bf5f29e56802f6321663f/charts/templates/_karmada_webhook_configuration.tpl#L61-L63

**Comment by RainbowMango** [comment]
I think so. But I'm afraid we might forget to update the template sometimes. Any ideas @jrkeen ?

**Comment by lonelyCZ** [comment]
> But I'm afraid we might forget to update the template sometimes.
Yes, I found the `ClusterOverridePolicy` is missed. Could I add it?

**Comment by jrkeen** [comment]
@lonelyCZ Yes, it is necessary.
For some reason, helm use `charts/templates/_karmada_webhook_configuration.tpl` instead of `artifacts/deploy/webhook-configuration.yaml`.

**Comment by XiShanYongYe-Chang** [comment]
Does `OverridePolicy` example in directory `/pkg/artifacts/example` need to be updated?

**Comment by XiShanYongYe-Chang** [comment]
> Does `OverridePolicy` example in directory `/pkg/artifacts/example` need to be updated?

Sorry for all, I see the changes on `example`.

**Comment by RainbowMango** [comment]
I just remember that the [webhook configuration] in karmadactl also needs to be updated.

**Comment by lonelyCZ** [comment]
> I just remember that the [webhook configuration] in karmadactl also needs to be updated.

Ok, I will do it.

**Comment by RainbowMango** [comment]
Thanks, I'm thinking if we can use [embed feature](https://pkg.go.dev/embed) to improve it.

**Comment by lonelyCZ** [comment]
> Thanks, I'm thinking if we can use [embed feature](https://pkg.go.dev/embed) to improve it.

Yes, I am also thinking it, including `crd`. When we compile `karmadactl` that should get `crd` or others file dynamically. But it need some time to research it.

We can directly modify it firstly and replace it with `embed feature` uniformly. I would like do it.

**Comment by RainbowMango** [comment]
> We can directly modify it firstly and replace it with embed feature uniformly. I would like do it.

nice.

**Comment by lonelyCZ** [comment]
> Thanks, I'm thinking if we can use [embed feature](https://pkg.go.dev/embed) to improve it.

Hi, @RainbowMango , I researched this feature these days, but it seem not to support access parent directory. So if using it, we also need to copy `crds` and `webhook config` to `pkg/karmadactl/cmdinit/`.

[https://go.googlesource.com/proposal/+/master/design/draft-embed.md](https://go.googlesource.com/proposal/+/master/design/draft-embed.md)
> Dot-dot, module boundaries, and file name restrictions
In order to build files embedded in a dependency, the raw files themselves must be included in module zip files. This implies that any embedded file must be in the module’s own file tree. It cannot be in a parent directory above the module root (like ../../../etc/passwd), it cannot be in a subdirectory that contains a different module, and it cannot be in a directory that would be left out of the module (like .git). Another implication is that it is not possible to embed two different files that differ only in the case of their file names, because those files would not be possible to extract on a case-insensitive system like Windows or macOS. So you can’t embed two files with different casings, like this:
>
> //go:embed README readme
But //go:embed dir/README other/readme is fine.
>
> Because embed.Files implements fs.FS, it cannot provide access to files with names beginning with .., so files in parent directories are also disallowed entirely, even when the parent directory named by .. does happen to be in the same module.

**Comment by RainbowMango** [comment]
I'll look at it later.
