### ISSUE TITLE
Karmada installer

### ISSUE THREAD

**Issue by riverzhang** [karmada-io/karmada#1276]
**Task description**:
I want to create a project with karmada installer. I am using Ansible to deploy Karmada(https://github.com/riverzhang/karmada-installer). Through this project, we integrate all current deployment approaches. Including Ansible + [Karmada Charts](https://github.com/karmada-io/karmada/tree/master/charts) and [Kubectl Karmada](https://github.com/karmada-io/karmada/tree/master/cmd/kubectl-karmada)，This allows users to have one more choice.

**Solution**:
Setup a Production Ready Karmada.
- [x] use[ ansible + karmada yaml file](https://github.com/riverzhang/karmada-installer) to install karmada control plane
- [ ] use ansible and kubectl-karmada to install karmada control plane
- [ ] use ansible and helm charts to install karmada control plane
- [ ] use binary install karmada
- [ ] install karmada addons
- [x] external etcd cluster support
- [x] use ansible to join or unjoin member cluster
- [ ] CI support([self-hosted runners on kubernetes,](https://medium.com/geekculture/github-actions-self-hosted-runner-on-kubernetes-55d077520a31) [kubevirt on kubernetes](https://kubevirt.io/labs/kubernetes/lab1.html),[Request Infrastructure in cncf cluster](https://github.com/cncf/cluster/issues)  ), unit-test -> create vms by kubevirt -> deploy 1 host k8s cluster + 2 member k8s cluster  by kubespray-> deploy karmada -> check karmada api ->  delete vms

karmada operator API
- [ ] It is a kubernetes operator deploy in meta kubernetes and manage karmada(create、scale、delete、upgrade、 fault self-healing, etc.)

**Who can join or take the task**:

**How to join or take the task**:

**How to ask for help**:

**Comment by RainbowMango** [comment]
Sounds like an interesting approach. 
Would you like to present a demo at the next 
[Community Meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit)?.

**Comment by riverzhang** [comment]
@RainbowMango Thanks, I can do it at the next meeting.

**Comment by riverzhang** [comment]
@RainbowMango  Can I Request physical resources from [cncf/cluster](https://github.com/cncf/cluster)? I want to build CI for karmada installer.

For example：unit-test -> create vms by kubevirt -> deploy 1 host k8s cluster + 2 member k8s cluster by kubespray-> deploy karmada -> check karmada api -> delete vms
1. deploy k8s cluster on packet.
2. [self-hosted runners on kubernetes,](https://medium.com/geekculture/github-actions-self-hosted-runner-on-kubernetes-55d077520a31) 
3. [kubevirt on kubernetes](https://kubevirt.io/labs/kubernetes/lab1.html)

**Comment by RainbowMango** [comment]
We can't do that by GitHub Action, right? Why?

> Can I Request physical resources from cncf/cluster?

Sure thing. But let's clarify why we need it before filing the request.
My concern is it may require more maintenance effort. So, we should clarify the benefits.

By the way, do you mean E2E test?  I don't think the unit test needs a real Karmada system.

**Comment by riverzhang** [comment]
CI demo:
https://github.com/riverzhang/karmada-installer/pull/2

**Comment by RainbowMango** [comment]
Are you going to show it at [next week's meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.zce53zltaf4n)? I haven't seen any agent yet.

**Comment by riverzhang** [comment]
Yes. I can't edit this document.

**Comment by riverzhang** [comment]
karmada  installer CI[](https://github.com/riverzhang/karmada-installer/pull/2/files#diff-097166ba52959e1c35488a1a891c6d60c6d875baae860b15c05e21151a92e9ea)

**Comment by riverzhang** [comment]
add [karmada  installer CI Architecture](https://github.com/riverzhang/karmada-installer/pull/2/files#diff-097166ba52959e1c35488a1a891c6d60c6d875baae860b15c05e21151a92e9ea)

**Comment by riverzhang** [comment]
@RainbowMango  @kevin-wangzefeng  According to the discussion at the meeting,  Can I Request physical resources from [cncf/cluster](https://github.com/cncf/cluster)? Or the community can provide other resources？ I want to build CI for karmada installer.

**Comment by RainbowMango** [comment]
I wonder if we can use `GitHubAction`?
(seems i asked the same question before, but i forgot the answer :( )

**Comment by riverzhang** [comment]
`I wonder if we can use GitHubAction?`
GitHubAction provides only one vm such as Ubuntu-18.04 by default. We can deploy many K8S clusters using KIND.

But now I expect to deploy many k8s clusters in vms, and karmada-installer CI deploys karmada through ssh login. Such as deploying karmada via binary, etc.   In this case, it would not be suitable. This approach may be more reasonable as the number of test scenarios increases in the future.
