### ISSUE TITLE
os.Exit() will broke the effect of defer function

### ISSUE THREAD

**Issue by kerthcet** [karmada-io/karmada#1313]
**What happened**:
```golang
func main() {
	logs.InitLogs()
	defer logs.FlushLogs()

	if err := xxx.Execute(); err != nil {
		os.Exit(1)
	}
}
```
`FlushLogs()`will not call if `os.Exit(1)`

**What you expected to happen**:
`FlushLogs()` should take effect even `Execute()` returns error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Similar to https://github.com/karmada-io/karmada/pull/1289#event-5943184872. Following up all related prs regarding to other components in this issue. 
Besides, each pr also solves other problems:
1. Repetitive printing error message due to cobra will also print error messages: https://github.com/karmada-io/karmada/blob/85554ff18796bbf3866ffe310cea8d8557b96105/vendor/github.com/spf13/cobra/command.go#L985-L987
2. Wrapping an error with %w makes it available to `errors.Is` and `errors.As``
3. Remove `os.Exit()` if possible

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

[edit by @RainbowMango]
- [x] karmada-scheduler (#1289)
- [x] karmada-agent(#1314)
- [x] karmada-aggregated-apiserver(#1315)
- [x] karmada-controller-manager(#1316)
- [x] karmadactl(#1317)
- [x] kubectl-karmada(#1318)
- [x] karmada-scheduler-estimator(#1319)
- [x] karmada-webhook(#1320)

**Comment by RainbowMango** [comment]
@lonelyCZ Could you please help review the relevant PRs of this issue?

**Comment by lonelyCZ** [comment]
> @lonelyCZ Could you please help review the relevant PRs of this issue?

Ok, thanks.
