### ISSUE TITLE
API group and kind improvement umbrella issue

### ISSUE THREAD

**Issue by kevin-wangzefeng** [karmada-io/karmada#140]
To simplify API and improve API self-explaination, we need to change the API group and kind as the following:

### Policy API Group: 
- [x] The group name, rename from `propagationstrategy.karmada.io` to `policy.karmada.io` (@kevin-wangzefeng #142)
- [x] Kinds under this group
    - [x] `PropagationPolicy`
    - [x] `ClusterPropagationPolicy` (@kevin-wangzefeng #185)
    - [x] `OverridePolicy`
    - [x] `ClusterOverridePolicy` （@kevin-wangzefeng #186）

### Work API group
- [x] The group name: `work.karmada.io` (@RainbowMango #195)
- [x] Kinds under this group:
    - [x] `ResourceBinding`, which is the replacement of current `PropagationBinding` (@RainbowMango #193)
    - [x] `ClusterResourceBinding`, indicates the binding relationship between ClusterPropagationPolicy and a cluster scoped resource (@RainbowMango #197)
    - [x] `Work`, which is the new name and place of `PropagationWork` (@RainbowMango #169)

### Cluster API Group
The API group for member cluster management relevant APIs
- [x] The group name, use `cluster.karmada.io` instead of current `membercluster.karmada.io` (@kevin-wangzefeng #139)
- [x] Kinds under this group:
    - [x] `Cluster`, to replace the kind `MemberClusrer` (@kevin-wangzefeng #139)
- [ ] Add integration support of Kubernetes Cluster API, need more idea input.

### Network API Group
The API Group for network relevant APIs including multi-cluster service discocery, multi-cluster load balancing, multi-cluster ingress etc.
- [ ] The group name: `network.karmada.io`
- [ ] Kinds under this group:
    - [ ] TBD
