### ISSUE TITLE
[umbrella] Grouping flags for components 

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1485]
**What would you like to be added**:
We have implemented to group flags for `karmada-controller-manager` at #1468  and `karmada-agent` at #1389 , and the other components also need to be implemented.

- [x] karmada-aggregated-apiserver (#1494 by @AllenZMC )
- [x] karmada-scheduler (#1491 by @jameszhangyukun )
- [x] karmada-descheduler (#1490 by @AllenZMC )
- [x] karmada-scheduler-estimator (#1493 by @AllenZMC )
- [x] karmada-webhook (#1488 by @AllenZMC )

**Why is this needed**:
