### ISSUE TITLE
TODO List: Enhance Cluster Lifecycle Management

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#1762]
**What would you like to be added**:
According to https://github.com/karmada-io/karmada/issues/1640#issuecomment-1119377312, I'd like to enhance cluster lifecycle management. Here is the todo-list.

- [x] Add a taint for the clusters which are unhealthy for a period of time.#1781
- [x] Add taint manager. #1945
- [x] Remove cluster scheduling result in `spec.clusters` when the cluster is terminating. #2373
- [ ] Remove `Failover` from scheduler. #2391

**Why is this needed**:
Move some functions away from scheduler and make the scheduler more concise.

**Comment by RainbowMango** [comment]
Hi @Garrybest 
I guess the task(`Remove cluster scheduling result in spec.clusters when the cluster is terminating.`) is included in #1945.

Should we update the task list?

**Comment by Garrybest** [comment]
> Hi @Garrybest I guess the task(`Remove cluster scheduling result in spec.clusters when the cluster is terminating.`) is included in #1945.
> 
> Should we update the task list?

Well, I'm afraid not. This task is to drain a cluster by using NoExecute taint when we decide to unjoin it, while #1945 focuses on how taint manager works.

**Comment by Garrybest** [comment]
I have an idea. Maybe we could implement this in cmd `karmadactl unjoin`. Just like what `kubectl drain` does, when we want to unjoin a cluster, we cordon this cluster first and then remove RB's cluster scheduling result in spec.clusters.

**Comment by RainbowMango** [comment]
Great thanks to @Garrybest !!!
