### ISSUE TITLE
Graceful eviction umbrella issue

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2281]
**What would you like to be added**:
We hope to introduce a `graceful` way to delay the removal until the resource is available on the substitute cluster.

Iterated task:
- [x] API change [#2273](https://github.com/karmada-io/karmada/pull/2273)
- [x] Introduce `GracefulEviction` feature gate. [#2340](https://github.com/karmada-io/karmada/pull/2340)
- [x] Make changes to `karmada-scheduler` to mark `schedulerObservedGeneration` (RB) [#2330](https://github.com/karmada-io/karmada/pull/2330)
- [x] Make changes to `karmada-scheduler` to mark `schedulerObservedGeneration` (CRB) [#2345](https://github.com/karmada-io/karmada/pull/2345)
- [x] Introduce `grace-eviction-controller` to implementers the API. ([#2319](https://github.com/karmada-io/karmada/pull/2319))
- [x] Make changes to `binding controller` to adopt the changes. ([#2339](https://github.com/karmada-io/karmada/pull/2339))
- [x] Make changes to `taint manager` to trigger graceful eviction. ([#2346](https://github.com/karmada-io/karmada/pull/2346))
- [ ] Introduce a documentation to https://karmada.io/docs/next/  (under Multi-cluster scheduling)

**Why is this needed**:
#1762 addresses the eviction feature that focuses on trigger eviction based on taints toleration and introduces a `taint manager` to perform the eviction.

Once the `taint manager` performs the eviction (means remove a specific cluster from the RB(`ResourceBinding`) target list(.spec.clusters)), the resource referenced by the RB will be `removed immediately from the target cluster. 

For example, there is an online workload(like an Nginx server) that was running on `cluster-1`, and then a network broken issue happens, Karmada starts to evict it from `cluster-1` and probably `karmada-scheuler` scheduled it to `cluster-2`. The thing is the workload would be removed immediately and no service available until the workload runs on `cluster-2`.

**Comment by XiShanYongYe-Chang** [comment]
I will continuously improve failover.
/close
