### ISSUE TITLE
[Umbrella] karmadactl uses factory instead of karmadaConfig

### ISSUE THREAD

**Issue by carlory** [karmada-io/karmada#2349]
**What would you like to be added**:

Iterated task:

- [x] karmadactl logs uses factory #2202
- [x] karmadactl apply uses factory
- [x] karmadactl describe uses factory #2471
- [x] karmadactl exec uses factory #2470
- [ ] karmadactl get uses factory 
- [ ] karmadactl promote uses factory
- [ ] karmadactl taint uses factory
- [ ] all sub command accepts factory as input parameter

**Why is this needed**:

At present, there are many places in karmadactl, which are building clients and factories for member cluster repeatedly, such as init, get, log, exec, etc. 

#2202  introduces factory interface, and try to resolve it.

/assign

**Comment by liangyuanpeng** [comment]
I would working for `karmadactl promote`.

**Comment by lonelyCZ** [comment]
> I would working for karmadactl promote.

Hi @liangyuanpeng , have it moved forward? 

And I consider to optimize the code style of karmadactl at #2664 , let's push ahead this issue.

**Comment by carlory** [comment]
/close
All tasks has been done
