### ISSUE TITLE
[Umbrella] interpreter enable `InterpretHealth` feature

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2354]
**What would you like to be added**:
We are going to enable `InterpretHealth` feature to [Resource Interpreter Framework](https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter). 

Iteration tasks:
- [x] Make changes to [Resource Interpreter Framework](https://github.com/karmada-io/karmada/tree/master/pkg/resourceinterpreter) to enable `InterpretHealth`. (#2329)
- [x] Make changes to [karmada webhook](https://github.com/karmada-io/karmada/blob/b1684b646622456dcd02fade751c0dca278b33b9/pkg/webhook/configuration/validating.go#L65) to remove the restriction. (#2329)
- [x] Make changes to `Resource Interpreter Framework` to add build-in/default interpreter for resources in [here](https://github.com/karmada-io/karmada/blob/b1684b646622456dcd02fade751c0dca278b33b9/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go#L25-L32).
- [x] Make changes to E2E tests to cover this feature. (#2416)

**Why is this needed**:
The [Graceful Eviction](https://github.com/karmada-io/karmada/issues/2281) feature needs to perform eviction/cleanup work as per resource health status.
