### ISSUE TITLE
[umbrella] Karmada proxy implementation

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#2372]
**What would you like to be added**:
We are going to introduce a new feature named proxy to adopt the [proposal](https://github.com/karmada-io/karmada/pull/2058).

I'd like to list all the iterated tasks here, anyone wants to join or help on it, please feel free to leave your comment on it.

- [x] proxy skeleton get on board. (@ikaven1024,  #2366)
- [x] Implement proxy cache reconcile logic. (@ikaven1024 #2389)
- [x] Update the proposal (@ikaven1024 , #2058)
- [x] Add a user guide document for proxy feature (@ikaven1024 https://github.com/karmada-io/website/pull/135)
- [x] add ut/e2e tests for proxy (@ikaven1024 https://github.com/karmada-io/karmada/pull/2414)
- [x] stress test for proxy (@ikaven1024 https://github.com/karmada-io/karmada/issues/2518)

Further tasks:
- fix workload status collecting error when override workload name in member clusters.
- rename search component name and API group name (TBD?)

**Why is this needed**:

**Comment by ikaven1024** [comment]
cc @RainbowMango

**Comment by RainbowMango** [comment]
Do you think we need a document for this feature?

**Comment by ikaven1024** [comment]
> Do you think we need a document for this feature?

Yes, i add it to the list.

**Comment by ikaven1024** [comment]
This stage is completed. Further works are doing int next stage.
/close
