### ISSUE TITLE
[umbrella]Karmada cluster resource modeling implementation

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#2379]
**What would you like to be added**:
We are going to implememt cluster resource modeling according to #772.

I'd like to list all the iterated tasks here, anyone wants to join or help on it, please feel free to leave your comment on it.

**Why is this needed**:

- [x] implement cluster API.  #2386 
- [x] implement the data struct. #2367 
- [x] add a new feature gate to enable cluster resource modeling. #2382 
- [x] make changes to cluster status controller to collect precise status. #2402 
- [x] make changes to karmada-AA to check input of cluster resource modeling. #2398 
- [x] make changes to scheduler to schedule based on cluster resource model. #2397 
- [x] user guide about custom cluster resource model. https://github.com/karmada-io/website/pull/139
- [x] UT and e2e https://github.com/karmada-io/karmada/pull/2431
