### ISSUE TITLE
[umbrella]Karmada search iterated tasks

### ISSUE THREAD

**Issue by liys87x** [karmada-io/karmada#2432]
**What would you like to be added**:
We are going to implememt karmada search.

I'd like to list all the iterated tasks here, anyone wants to join or help on it, please feel free to leave your comment on it.

**Why is this needed**:

- [ ] User guide for karmada search
- [ ] Search api supports query through backend
- [ ] Implement resource registry status
- [ ] Provides an example of an opensearch based dashboard
- [ ] Add election logic to let the leader write to the backend storage

**Comment by ikaven1024** [comment]
Proxy has been added in search. Shall we refactor search, fetch data from proxy cache, instead of informing from member clusters?

**Comment by liys87x** [comment]
Yes, we should store unified. But cache is more complex than informer and I needs a more comprehensive understanding.

**Comment by liys87x** [comment]
@ikaven1024 Currently cacheproxy is private, should it be exposed first?

**Comment by ikaven1024** [comment]
> @ikaven1024 Currently cacheproxy is private, should it be exposed first?

You shall use this interface, not cacheProxy:

https://github.com/karmada-io/karmada/blob/2b7ed24875f3914a68b3bb618799fa6d1e4fba37/pkg/search/proxy/store/multi_cluster_cache.go#L32-L37

**Comment by liys87x** [comment]
> 

How do I get its implementation, or rather, how do I get the MultiClusterCache

**Comment by ikaven1024** [comment]
> How do I get its implementation, or rather, how do I get the MultiClusterCache

You can add a method in proxy controller to export it.

**Comment by ikaven1024** [comment]
@liys87x proxy benchmark is done, what do you think about it? https://github.com/karmada-io/karmada/issues/2518#issue-1375349836
