### ISSUE TITLE
[umbrella] Use scale subresource to get or revise workload replica

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#2486]
**What would you like to be added**:

As discussed in #1397,  the scale subresource can be used to obtain or revise the number of resource replicas, which prevents users from implementing interpreter webhook and reduces remote invocation.

- [ ] get replicas with scale subresource #1728 
- [ ] revise replicas with scale subresource
- [ ] add e2e to coverage the cases 

**Why is this needed**:

**Comment by yusank** [comment]
To avoid code conflict, wait for PR #1728 merges, after that will submit code for `revise replicas with scale subresource` and `e2e test`

**Comment by XiShanYongYe-Chang** [comment]
We plan to close this task refer to https://github.com/karmada-io/karmada/pull/1728#issuecomment-1331625519
/close
