### ISSUE TITLE
Scheduler: Assignment Algorithm Refactor TODO List

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#2834]
Now the assginment algorithm and code structure is complex, I'm trying to refactor the algorithms.

- [x] refactor assign replicas strategy #2827
- [x] refactor static weight dividing strategy #2845
- [x] refactor dynamic weight dividing strategy #2946
- [x] refactor aggregated dividing strategy #2946
- [ ] refactor job completion dividing algorithm #2964
