### ISSUE TITLE
[Umbrella] Karmada Operator Plan (First Version) 

### ISSUE THREAD

**Issue by carlory** [karmada-io/karmada#2979]
- [x] Karmada CRD #2953
- [x] Operator  Skeleton #2973 
- [ ] Update scripts, makefile and workflows
- [ ] Operator Webhooks ( It is built into the operator)
       - possible solution 1: #2992 
       - possible solution 2: #3023
- [ ] operator implementation (draft) 
       - possible solution 1: #2990 
       - possible solution 2 (recommend https://github.com/karmada-io/karmada/pull/3102#issuecomment-1414662967): #3102
       We need to discuss, which implementation to use
- [ ] Etcd HA

/assign

**Comment by carlory** [comment]
- What is the relationship between Karmada Operator and Karmadactl?

Refactor Karmadactl, use Karmada Operator to manage and create Karmada instances. Consider init/deinit for now

- Karmada Operator’s early contribution and collaboration methods, regular community meetings, or Karmada Operator’s community meetings for independent issues?

git issue + regular community meeting

- Is the management of the Proposal in the Karmada main library or in the Karmada Operator? The Proposal in the Karmada community has no way to determine the actual progress of its associated functions based on the Proposal document.

Early stage No Proposal.

- What is the scope of responsibility of the Karmada operator? For dependencies such as etcd.opensearch, use the same support granularity to develop an etcd-operator within the karmada-operator?

Built-in, simple and highly available etcd cluster

- Karmada operator certificate management, self-signed or support community solutions such as cert-manager at the same time?

The first version is self-signed, and the follow-up integration

- What version range of Karmada does Karmada Operator support to install? < 1.0 Is it in the supported list?

The first version of Mouding v1.4, each version of Karmada Operator has a supported Karmada version range. Try to support a large version space

- When Karmada Operator itself is installed and deployed, what are the requirements for the host cluster version? 1.16 and above?

The first version supports 1.16, CI added

- When Karmada Operator exposes the service address to the outside world, should it natively support solutions such as MetalLB?

The first version supports external exposure of services, and the first version and the next version support external load balancing

- How does Karmada Operator support the creation of Karmada instances on remote clusters? When the cluster where Karmada Operator is located hangs (unrecoverable), how does the Karmada instance on the remote cluster ensure that its update and daily operation and maintenance are not affected?

To be discussed, first covered in the current cluster

- Does the Karmada Operator cover the migration of a Karmada instance from one cluster to another without affecting business? Can the Karmada Operator automatically migrate to another cluster synchronously during this process?

Subsequent planning, cluster upgrade, active-active

**Comment by RainbowMango** [comment]
> Operator Webhooks

Is it a standalone component? If yes, I suggest using controllers to reconcile(including validating and mutating) the objects. We can add some events or statuses to represent the validating results. 
My concern is if the operator requires additional components would discourage people to try it.

**Comment by wongearl** [comment]
Why didn't development continue on the karmada-operator project?

**Comment by carlory** [comment]
@wongearl see https://github.com/karmada-io/karmada-operator/pull/5#issuecomment-1346005511

**Comment by RainbowMango** [comment]
Hi @carlory Can you help to update the status of tracked tasks? I'm kind of lost, don't know which PR would be the next.
