### ISSUE TITLE
[lfx-mentorship-2023-March-May] Provide interactive environments

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3085]
**CNCF LFX mentorship**
https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/01-Mar-May

Mentor: @jwcesign 
Backup: @RainbowMango 

**What would you like to be added**:
Add Karmada starting examples with [killercoda](https://killercoda.com/), including a CLI installation example and script installation example, both containing installation and deploying workload to multi-clusters steps.

**Why is this needed**:
There are the following benefits:
* Some users don't have an environment to launch Karmada, it's more convenient for them if there is an out-of-box experiment environment.
* Users can learn easily with an out-of-box experiment environment with killercoda.

**Tasks**:
- [ ] Implement CLI installation example, with deploying workload to multi-clusters steps.
- [ ] Implement script installation example, with deploying workload to multi-clusters steps.
- [ ] Update Karmada official website docs, indicating users can quickly try Karmada with killercoda.

**Comment by johurul000** [comment]
@RainbowMango do you mean a tutorial like this one:
https://killercoda.com/thanos
I have did solve a small bug in this tutorial repository,
https://github.com/thanos-io/tutorials/tree/main/2-lts

**Comment by RainbowMango** [comment]
Yes, exactly.

**Comment by PaarthAgarwal** [comment]
@RainbowMango are there any prerequisite tasks?

**Comment by JadeFlute0127** [comment]
hi,I am a  master from sel laboratory of Zhejiang University, familiar with cloud native technology, and have used Killercoda to build a k8s cluster. Now I am very interested in the Karmada community and hope to participate in the community through this issue.

**Comment by alexr018350** [comment]
@RainbowMango I am looking forward to work on this project. Excited to work on the Karmada starting examples with killercoda, including CLI installation example and script installation example, both with deploying workload to multi-clusters steps as well as updating Karmada website.

**Comment by RainbowMango** [comment]
/close
The relevant task will be tracked by https://github.com/karmada-io/playground/issues/1.

/assign @JadeFlute0127
