### ISSUE TITLE
[umbrella] Add multiple scheduling group

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3153]
Refer to #3126 

Task breakdown list:
- [x] Add multiple scheduling group proposal #3126 
- [x] API modification adaptation #3105 #3163 #3172 
- [x] `karmada-controller-manager`: when creating or updating rb/crb, the added OrderedClusterAffinities in pp/cpp should be synced (The adaptation has been modified in #2702 .)
- [x] `karmada-scheduler`: invoke multi times `ScheduleAlgorithm interface` until the schedule succeeds (Adapt #3165 modification, add an input parameter to indicate the affinityName that is being processed.)
    - [x] add binding status in the schedule algorithm interface #3209 
    - [x] modify judgement of placement changed and consider clusteraffinities #3211
    - [x] invoke multi time with schedule algorithm #3181 
    - [x] update event handler to consider clusteraffinities #3181 
- [x] `karmada-webhook`: New field validation #3164 
- [x] E2E
  - [x] Workload propagating with scheduling type Duplicated #3219 
  - [ ] Workload propagating with scheduling type Divided
  - [x] Failover scenario #3219

**Comment by RainbowMango** [comment]
Please consider if we need to update the logic of policy changed or not at:
https://github.com/karmada-io/karmada/blob/e523977cb0b8eb0367dd7bfb9ac5820c235f2a47/pkg/scheduler/scheduler.go#L368-L374

and 
https://github.com/karmada-io/karmada/blob/e523977cb0b8eb0367dd7bfb9ac5820c235f2a47/pkg/scheduler/scheduler.go#L430-L435

**Comment by XiShanYongYe-Chang** [comment]
We have completed the development and testing of this feature,
/close

**Comment by RainbowMango** [comment]
> Workload propagating with scheduling type Divided

How to track this issue?

**Comment by XiShanYongYe-Chang** [comment]
> > Workload propagating with scheduling type Divided
> 
> How to track this issue?

Tracked by #3223
