### ISSUE TITLE
[Umbrella] Implement application failover

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3169]
Refer to #3133 

Task breakdown list:

Failover based on application state:
- [ ] Introduce a new `Failover` field for `PropagationSpec`.
- [ ] Binding API modification adaptation to implement application failover.
- [ ] `karmada-controller-manager`: introduce a new controller which will watch the change of the health field of ResourceBindingStatus, determine whether the failover condition is reached, and trigger the failover.
- [ ] `karmada-scheduler`: Add a new filter plugin, to filter the evicted cluster.
- [ ] `karmada-webhook`: Perform extra validation work to prevent misleading configuration.
- [ ] E2E
- [ ] Document update.

**Comment by RainbowMango** [comment]
We haven't made the final decision yet. Please list the iteration tasks in the proposal.

And you can re-open it once we reached an agreement. 
/close
