### ISSUE TITLE
Improve FieldSelector of OverridePolicy

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3188]
**What would you like to be added**:

The [.targetCluster.fieldSelector] has some restrictions:
- The expression `key` should be one of the `provider`/`region`/`zone`.
- the expression `operator` should be one of the `In`/`NotIn`
The rules are exactly the same with PropagationPolicy, see [ValidatePolicyFieldSelector](https://github.com/karmada-io/karmada/blob/ea497819f0ee883c8f46fbb390ac540df27f2b0b/pkg/util/validation/validation.go#L71-L92).

Things we can do cloud be split into the following iteration tasks:
- [x] Update the [OverridePolicy filedSelector](https://karmada.io/docs/userguide/scheduling/override-policy#fieldselector) documents to note this restriction. (@fengshunli, [#314](https://github.com/karmada-io/website/pull/314))
- [x] Add validations to webhook just like [what we did for PropagationPolicy](https://github.com/karmada-io/karmada/blob/ea497819f0ee883c8f46fbb390ac540df27f2b0b/pkg/util/validation/validation.go#L72). (@chaunceyjiang, [#3193](https://github.com/karmada-io/karmada/pull/3193))
- [x] Refine the [TestClusterMatches](https://github.com/karmada-io/karmada/blob/master/pkg/util/selector_test.go#L291) (@Fish-pro, [#3192](https://github.com/karmada-io/karmada/pull/3192))
- [x] Note the restriction on APIs. (@RainbowMango, [#3242](https://github.com/karmada-io/karmada/pull/3242))

**Why is this needed**:
We should add documents for the restriction to avoid issues like #3186.

/help

**Comment by chaunceyjiang** [comment]
Can i pick some task?

**Comment by fengshunli** [comment]
Update the [OverridePolicy filedSelector](https://karmada.io/docs/userguide/scheduling/override-policy#fieldselector) documents to note this restriction.  assigned to me

**Comment by chaunceyjiang** [comment]
> Add validations to webhook just like [what we did for PropagationPolicy](https://github.com/karmada-io/karmada/blob/ea497819f0ee883c8f46fbb390ac540df27f2b0b/pkg/util/validation/validation.go#L72).

please assign it to me.

**Comment by RainbowMango** [comment]
Done.

**Comment by Fish-pro** [comment]
> Refine the [TestClusterMatches](https://github.com/karmada-io/karmada/blob/master/pkg/util/selector_test.go#L291)
@RainbowMango Could you assign it to me？

**Comment by fengshunli** [comment]
The document states that it is enough to add a type description of the provider, right? @RainbowMango

**Comment by RainbowMango** [comment]
The documents now only introduce how to use the `fieldSelector`, but don't note which `keys` and `operators` are supported.

**Comment by fengshunli** [comment]
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/18587688/220845522-d778eb8f-3b84-42a0-9b72-344e243fffa7.png">
Add the support description of the provider here, right?

**Comment by RainbowMango** [comment]
Wow, I didn't realize there was already something there.
But I'm thinking to give more clear instructions at [here](https://karmada.io/docs/userguide/scheduling/override-policy/#fieldselector), including supported fields and operators.

**Comment by fengshunli** [comment]
see https://github.com/karmada-io/website/pull/314

**Comment by RainbowMango** [comment]
Thanks, I'll look at it tomorrow.
