### ISSUE TITLE
Add third-party resources into the Resource Interpreter framework

### ISSUE THREAD

**Issue by yike21** [karmada-io/karmada#3331]
**What would you like to be added**:
Karmada's Resource Interpreter Framework is designed for interpreting resource structure. It consists of built-in and customized interpreters. Karmada could bundle some popular and open-sourced resources so that users can save the effort to customize them.

**Tasks**:
1. Argo Workflow  (deadline: April 23, 2023)
    group: argoproj.io
    version: v1alpha1
    - [x] Implement resoucecustomization for  Workflow, including `InterpretReplica`, `ReviseReplica`, `Retain`,  `InterpretDependency`,`InterpretHealthy`. #3438 

2. Flux CD (deadline: April 30, 2023)
    group: source.toolkit.fluxcd.io
    version: v1
    - [x] implement resoucecustomization for  GitRepository, including `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`. #3481 

    group: source.toolkit.fluxcd.io
    version: v1beta2
    - [x] implement resoucecustomization for OCIRepository, including `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`. #3482
    - [x] implement resourcecustomization for HelmRepository, including `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`. #3484
    - [x] implement resoucecustomization for Bucket, including `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`. #3485 
    - [x] implement resourcecustomization for HelmChart, including `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`. #3486 

    group: kustomize.toolkit.fluxcd.io
    version: v1
    - [x] implement resoucecustomization for Kustomization, including `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`. #3487 

    group: helm.toolkit.fluxcd.io
    version: v2beta1
    - [x] implement resoucecustomization for HelmRelease, including `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`. #3488
    
3. Kyverno (deadline: May 10, 2023)
    group: kyverno.io    
    version: v1
    - [x] Implement resoucecustomization for Policy, including `AggregateStatus`, `InterpretStatus`, `InterpretHealth`. #3498 
    - [x] Implement resoucecustomization for ClusterPolicy, including `AggregateStatus`, `InterpretStatus`, `InterpretHealth`. #3499 
    
4. OpenKruise (deadline: ~April 1, 2023~ April 4, 2023)
    group: apps.kruise.io    
    version: v1alpha1
    - [x] Implement resoucecustomization for CloneSet, including `InterpretReplica`, `ReviseReplica`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`, `InterpretHealthy`.#3337
    - [x] Implement resourcecustomization for AdvancedDaemonSet, including `AggregateStatus`, `InterpretStatus`, `InterpretDependency`, `InterpretHealthy`.#3358
    - [x] Implement resourcecustomization for BroadcastJob, including `InterpretReplica`, `ReviseReplica`, `Retain`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`,`InterpretHealthy`.#3366
    - [x] Implement resourcecustomization for AdvancedCronJob, including `AggregateStatus`, `InterpretDependency`, `InterpretHealthy`.#3368 

    group: apps.kruise.io    
    version: v1beta1
    - [x] Implement resourcecustomization for AdvancedStatefulSet, including `InterpretReplica`, `ReviseReplica`, `AggregateStatus`, `InterpretStatus`, `InterpretDependency`, `InterpretHealthy`.#3352

  Others those should be implemented.
  - [x] #3339
  - [x] update the document. https://github.com/karmada-io/website/pull/360

**Why is this needed**:

**Comment by yike21** [comment]
*journal*: 
1.When using the duplicated propagation strategy, the `daemonset(apps.kruise.io/v1alpha1)` is propagated to cluster member1 and cluster member3. It is found that the generation of member1 and member3 is 1, but the generation observed by karmada-apiserver is 2 according to ResourceBinding.  
2.`Update resourceBinding(test-kruise-deamonset/sample-daemonset) with AggregatedStatus successfully` but there is no 
`.status` attribute in sample which is a `daemonset.apps.kruise.io`. The ResourceBinding has appropriate infomation ( except `.metadate.generation` and `.status.schedulerObservedGeneration`)
And I have to put off the deadline of ***Task 4***.

**Comment by yike21** [comment]
The project was successfully completed. Thanks to the mentors for your guidance! @Poor12 @chaunceyjiang @RainbowMango @XiShanYongYe-Chang 
Thanks all for your help!

**Comment by RainbowMango** [comment]
Good Job! @yike21  As well as the mentor team!
