### ISSUE TITLE
[umbrella] Add Implementation for PropagationPolicy priority and preemption

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3787]
**What would you like to be added**:
In #3684, we propose a mechanism for PropagationPolicy priority and preemption.

The specific work items are as follows:

- [x] add `preemption` field for pp/cpp
- [x] add a new feature gate for preemption @Poor12 
- [x] add validation for resourceSelector if the policy enables preemption @whitewindmills 
- [x] extend the detector to implement preemption of high-priority pp/cpp -> low-priority pp/cpp @whitewindmills 
- [x] extend the detector to implement preemption of pp -> cpp @whitewindmills 
- [x] metrics and events about preemption operation
- [ ] add E2E coverage for the scenario for preemption
- [ ] document update
- [x] [Corner case recognized for PropagationPolicy](https://github.com/karmada-io/karmada/pull/3684#issuecomment-1645075275): How to transfer control to another PP/CPP during de-prioritize a PP/CPP? (#3965, @RainbowMango)
- [x] Corner case solution for ClusterPropagationPolicy.  (#3990, @chaosi-zju)

**Why is this needed**:

Ref proposal #3684

**Comment by whitewindmills** [comment]
the first two are fine for me.
/assign

**Comment by RainbowMango** [comment]
@whitewindmills The first task [is here](https://github.com/karmada-io/karmada/pull/3788) and you can help to review now.

**Comment by Poor12** [comment]
Thanks @whitewindmills. Before you started the task, I'd like to ensure that you have enough time and be able to merge it before 7.25. If you are ok, I'd like to help you complete it. :)

**Comment by RainbowMango** [comment]
> extend the detector to implement preemption of pp/cpp

I'm thinking if we can split the implementation into some small tasks. That will be easier to iterate and manage the progress.

**Comment by whitewindmills** [comment]
> Thanks @whitewindmills. Before you start the task, I'd like to ensure that you have enough time and be able to merge it before 7.25. If you are ok, I'd like to help you complete it. :)

sure, glad to see you are willing to help me with this task. I have put it at the top of my work queue, I will submit a PR as soon as possible.

**Comment by whitewindmills** [comment]
> I'm thinking if we can split the implementation into some small tasks. That will be easier to iterate and manage the progress.

if split, I'll pick one.

**Comment by Poor12** [comment]
I have split it into some pieces of tasks. You can go ahead and implement the data structure first. @whitewindmills

**Comment by whitewindmills** [comment]
> You can go ahead and implement the data structure first.

@Poor12 Hi, you can help review it now.

**Comment by whitewindmills** [comment]
I'll work on `add validation for resourceSelector if the policy enables preemption` first.

**Comment by RainbowMango** [comment]
Hi @whitewindmills I just sent a PR(#3965) for the corner case we discussed at https://github.com/karmada-io/karmada/pull/3684#issuecomment-1645075275. Could you please take a look?
