### ISSUE TITLE
Cleanup deprecated methods in wait package

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3835]
**What would you like to be added**:

- [x] Update `wait.Poll` to `wait.PollUntilContextTimeout` (with `immediately = false`)  (@Affan-7, #3906 )
For example:
```diff
--- a/pkg/controllers/certificate/cert_rotation_controller.go
+++ b/pkg/controllers/certificate/cert_rotation_controller.go
@@ -165,7 +165,7 @@ func (c *CertRotationController) syncCertRotation(secret *corev1.Secret) error {

        var newCertData []byte
        klog.V(1).Infof("Waiting for the client certificate to be issued")
-       err = wait.Poll(1*time.Second, 5*time.Minute, func() (done bool, err error) {
+       err = wait.PollUntilContextTimeout(context.TODO(), 1*time.Second, 5*time.Minute, false, func(ctx context.Context) (done bool, err error) {
                csr, err := c.KubeClient.CertificatesV1().CertificateSigningRequests().Get(context.TODO(), csr, metav1.GetOptions{})
                if err != nil {
                        return false, fmt.Errorf("failed to get the cluster csr %s. err: %v", clusterName, err)
```

- [x] Update `wait.PollImmediate` to `wait.PollUntilContextTimeout` (with `immediately = true`)  (@liangyuanpeng, #3921)
For example:
```diff
diff --git a/pkg/controllers/cluster/cluster_controller.go b/pkg/controllers/cluster/cluster_controller.go
index ae123a86e..678bf7188 100644
--- a/pkg/controllers/cluster/cluster_controller.go
+++ b/pkg/controllers/cluster/cluster_controller.go
@@ -394,7 +394,7 @@ func (c *Controller) monitorClusterHealth(ctx context.Context) (err error) {
        for i := range clusters {
                cluster := &clusters[i]
                var observedReadyCondition, currentReadyCondition *metav1.Condition
-               if err = wait.PollImmediate(MonitorRetrySleepTime, MonitorRetrySleepTime*HealthUpdateRetry, func() (bool, error) {
+               if err = wait.PollUntilContextTimeout(ctx, MonitorRetrySleepTime, MonitorRetrySleepTime*HealthUpdateRetry, true, func(ctx context.Context) (bool, error) {
                        // Cluster object may be changed in this function.
                        observedReadyCondition, currentReadyCondition, err = c.tryUpdateClusterHealth(ctx, cluster)
                        if err == nil {

```

- [x] Update `wait.PollUntil` to `PollUntilContextCancel` (@zhzhuang-zju, [#4947](https://github.com/karmada-io/karmada/pull/4947))

This might be a little bit challenging, we need to transition channel to context. Probably could leverage [ContextForChannel](https://github.com/karmada-io/karmada/blob/e5277b6317ac1a4717f5fac4057caf51a5d248fc/pkg/util/context.go#L11).

- [x] Enable static check by removing [these lines](https://github.com/karmada-io/karmada/blame/e5277b6317ac1a4717f5fac4057caf51a5d248fc/.golangci.yml#L69-L72) (@RainbowMango, #4992)

**Why is this needed**:
The `wait.PollImmediate`, `wait.Poll`, etc methods were deprecated in Kubernetes v1.27 ([#107826](https://github.com/kubernetes/kubernetes/pull/107826)), lint check is falling during update the dependencies of Kubernetes at #3730.
This kind of check has been disabled by #3730 to avoid huge modifications.

```
test/e2e/framework/cluster.go:320:9: SA1019: wait.PollImmediate is deprecated: This method does not return errors from context, use PollWithContextTimeout. Note that the new method will no longer return ErrWaitTimeout and instead return errors defined by the context package. Will be removed in a future release. (staticcheck)
	return wait.PollImmediate(2*time.Second, 10*time.Second, func() (done bool, err error) {
```

**Comment by liangyuanpeng** [comment]
So it's pending for https://github.com/karmada-io/karmada/pull/3730 if i'm understand correctly.

/assign

**Comment by RainbowMango** [comment]
Yes, exactly.

**Comment by RainbowMango** [comment]
Hi @liangyuanpeng I added some examples to the issue description, considering that the amount of changes may be relatively large, I have split these tasks into some interactive tasks. Hope this may make the review process more easier.

**Comment by Affan-7** [comment]
Can I work on this?

**Comment by RainbowMango** [comment]
@Affan-7 Sure. How about taking the first one as a start? `Update wait.Poll to wait.PollUntilContextTimeout (with immediately = false)`

**Comment by Affan-7** [comment]
Thanks @RainbowMango.

/assign

**Comment by liangyuanpeng** [comment]
@RainbowMango  Thanks for tasks list and seems like it's lost the `wait. poll`, please help to put it up and i'm taking the `wait. poll` and `wait. PollImmediate`

**Comment by liangyuanpeng** [comment]
Please check the https://github.com/kubernetes/kubernetes/pull/119762 before working for ` Update wait.PollUntil to PollUntilContextCancel`

Seems like the `PollUntilContextCancel immediately`  have some problem.

**Comment by RainbowMango** [comment]
Thanks @liangyuanpeng for the update, While migrating the `wait.Poll` to `wait.PollUntilContextTimeout`, we are currently blocked by weird failing tests. I'm not sure if it is the same issue yet.

**Comment by wlq1212** [comment]
Can I work on this?

 @RainbowMango

**Comment by Rei1010** [comment]
@RainbowMango anything I can do？

**Comment by RainbowMango** [comment]
@wlq1212 @Rei1010 Sure, thank you both in advance. There are two tasks left, please feel free to help with that.
But it seems https://github.com/kubernetes/kubernetes/pull/119762 blocks this issue, I guess we need to wait for a while until there is an official Kubernetes release comes out.

I'll let you know once we are able to do it.

**Comment by liangyuanpeng** [comment]
Have create PR https://github.com/kubernetes/kubernetes/pull/122119 to cherrypick kubernetes#119762 for kubernetes v1.27, once it's merge, we can keeping going.

**Comment by RainbowMango** [comment]
@zhzhuang-zju Would you like to help with this?
You can get started by `Update wait.PollUntil to PollUntilContextCancel`.

**Comment by zhzhuang-zju** [comment]
> @zhzhuang-zju Would you like to help with this?

Sure, I would.

**Comment by liangyuanpeng** [comment]
seems like i missed the ping, let's keep going  :hammer:
