### ISSUE TITLE
[lfx-mentorship-2023-Sep-Nov] supports promote dependent resources automatically

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3842]
**CNCF LFX mentorship**
https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/03-Sep-Nov

Mentor: @jwcesign 
Backup: @RainbowMango 

**What would you like to be added:**
Provide an automatic promotion mechanism for dependent resources in karmadactl. When promoting a resource, all the resources that it depends on will be automatically promoted as well. For example, promoting the Secret that is dependent by a Deployment.

**Why is this needed:**

Related issue: #1862 

**Tasks:**

TDB

**Comment by zhy76** [comment]
I am interested in this and would like to apply for lfx.

**Comment by XiShanYongYe-Chang** [comment]
Now we are still in the project proposal stage. According to the [timeline](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/03-Sep-Nov#term-03---2023-september---november), mentees can start applying at the time `Wed Aug 16 - Tues Aug 29, 5:00 PM PDT`.

**Comment by AdiAkhileshSingh15** [comment]
Hey,
I'm interested in this project and I plan to apply as a Mentee once LFX Fall applications are open. 
Also, I'm curious to know if there are any beginner-friendly issues available for me to start contributing and get to know more about the project.

Any help would be highly appreciated.
Thanks!

**Comment by YashPimple** [comment]
Hello [XiShanYongYe-Chang](https://github.com/XiShanYongYe-Chang) I am interested in learning about this project and want to work on this project under LFX Mentorship **Karmada supports promote dependent resources automatically**
also, this issue seems like a great starting point for getting started with a contribution to the Karmada. Landed here from the [CNCF mentorship repository](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/03-Sep-Nov#karmada-supports-promote-dependent-resources-automatically)

Additionally, I was wondering if there is anything else I can do to get started, such as research, and will learn about the project from the existing documentation.

**Comment by tamil07** [comment]
Hi, I am interested to contribute to this project but not as a Mentee but just as a part time as I don't wish to get paid. 
Would it be possible to so?

**Comment by XiShanYongYe-Chang** [comment]
> Hi, I am interested to contribute to this project but not as a Mentee but just as a part time as I don't wish to get paid.
> Would it be possible to so?

Hi @tamil07, thank you very much for participating in the open-source activities of the Karmada community. I believe that you can contribute to the entire project, such as solution design, code review, test design and execution, documentation writing and promotion, and so on.

**Comment by AvineshTripathi** [comment]
Hey @XiShanYongYe-Chang wrt to this issue I looked after the normal promote feature PR with -d=true flag and based on discussion I can see the main task is to give support for CRD and for not only promote  command with dep but also advance scheduling that  cannot be done as finding dependency is a problem(https://karmada.io/docs/v1.3/userguide/globalview/customizing-resource-interpreter/#interpretdependency) 

I tried looking for ways to get dependecies for CRDS but still have no success finding one! wanted to ask if there are any discussions wrt to it where any rough solutions was discussed so that I can deep dive those and work in similar direction for possible solutions

**Comment by XiShanYongYe-Chang** [comment]
cc the owner @jwcesign to help take an answer.

**Comment by jwcesign** [comment]
To automatically promote the dependency resource, we need to identify the specific resources on which it depends. There are two methods for parsing these dependencies: through a webhook or using Lua. Here are the steps involved in each approach:

1. Using a webhook:
   - karmadactl sends a request to the webhook and parses the dependencies.
   - Based on this information, it creates the corresponding resource template and PropagationPolicy in the karmada control plane.
   - Note that requesting the webhook may pose difficulties, such as requiring port-forwarding.

2. Using Lua configuration:
   - karmadactl retrieves the Lua configuration and parses the dependencies.
   - It then generates the relevant resource template and pp in the Karmada control plane.

/cc @AvineshTripathi

**Comment by AvineshTripathi** [comment]
Thanks @jwcesign  for the description I'll look into the lua interpretor today. Does that also find dependency or does it only generates the template?

**Comment by jwcesign** [comment]
> Does that also find dependency or does it only generates the template?

Hi, @AdiAkhileshSingh15 , It only finds the dependencies.

**Comment by zhy76** [comment]
I have a question after studying this problem. Karmada already supports two methods of interpreting crd: 
1. webhook interpreter.
2. configuration interpreter. 

Both methods can query the dependencies of resources. It seems that we only need to get the obj of the resources that need to be promoted in the member cluster during the promotion process, call `ResourceInterpreter.GetDependencies(obj)` to get the dependency information of the resources, create  resource template and corresponding PP for each dependency. 
Is my understanding correct? What points need to be paid attention to in this process? Thanks~

**Comment by jwcesign** [comment]
Hi @zhy76, the main issue is how to implement it with karmadactl. From the perspective of karmada components, this is not difficult:
1. webhook interpreter - call the webhook service from the Karmada components.
2. configuration interpreter - call it with Luva engine.

**Comment by zhy76** [comment]
Task to be done:

- [ ] supports promote native dependent resources automatically.
- [ ] supports promote thirdparty dependent resources automatically.
- [ ] supports promote CRD dependent resources automatically.
    - [ ] webhook interpreter adapter implement to getdependencies.
    - [ ] use configuration interpreter to get dependencies.
- [ ] E2E tests.
- [ ] Doc update.

**Comment by jwcesign** [comment]
Hi, we need a proposal first. Can we add it to tasks?

**Comment by XiShanYongYe-Chang** [comment]
Hi @jwcesign @zhy76  The current issue is used for the release of LFX tasks. A new issue can be submitted to manage tasks.

**Comment by zhy76** [comment]
> Hi @jwcesign @zhy76 The current issue is used for the release of LFX tasks. A new issue can be submitted to manage tasks.

OK, I will submit a new issue.

**Comment by XiShanYongYe-Chang** [comment]
Thank you to everyone interested in Karmada. Next year, the lfx Karmada community will also apply for more projects. Please continue to stay tuned.

It will be tracked by #4036. 
/close
