### ISSUE TITLE
[umbrella] grant admin clusterrole with karamda resource permission

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3916]
**What would you like to be added**:

`admin` is a built-in ClusterRole in Kubernetes, refer to [User-facing roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles). In karmada, we need to grant `admin` clusterrole with karamda resource permission, such as `propagationpolicics`,`resourcebindings`, `works`, etc.

**Why is this needed**:

By binding with `rolebing`, users are able to have read and write permissions for all resources within the namespace (except resourcequotas and federatedresourcequotas).

**Task Decomposition**

The specific work items are as follows:

- [x] adaptation of `hack` installation method #3915 
- [x] adaptation of `karmadactl init` installation method @zhy76 #3937 
- [x] adaptation of `helm chart` installation method @Vacant2333 #3957
- [x] adaptation of `operator` installation method @Vacant2333 #3953
- [x] update karmada [document site content](https://karmada.io/docs/next/administrator/configuration/configure-controllers#required-controllers) https://github.com/karmada-io/website/pull/450
- [x] include it in upgrading documents.

**Comment by XiShanYongYe-Chang** [comment]
> I want to help 😄

Ok, thanks 👍 You can choose a few small tasks that you want to do, and I will assign them to you afterwards.

**Comment by zhy76** [comment]
OK, I will check out `adaptation of karmadactl init installation method`

**Comment by Vacant2333** [comment]
i want to help `adaptation of helm chart installation method` and  `adaptation of operator installation method` ~

**Comment by XiShanYongYe-Chang** [comment]
Let me try to see if I can assign multiple people.
/assign @zhy76 @Vacant2333 @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
All tasks have been completed, thank you everyone~
/close
