### ISSUE TITLE
umbrella issue: deprecating zones in Cluster API

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3952]
**What would you like to be added**:
This issue tracks subsequent tasks of [deprecating zone with zones](https://github.com/karmada-io/karmada/pull/3933).

- [x] Add validation for `zones`, possibly at [here](https://github.com/karmada-io/karmada/blob/276d6a8ad1f156546a3208aefb26ceb3252c3a7f/pkg/apis/cluster/validation/validation.go#L152-L164). (@zishen, #3975)
In addition, we should ensure that `zone` and `zones` will not co-exist.
- [x] Transform potential `zone` to `zones`, possibly at [here](https://github.com/karmada-io/karmada/blob/276d6a8ad1f156546a3208aefb26ceb3252c3a7f/pkg/registry/cluster/strategy.go#L129-L132). (@zishen, #3983)
- [x] Deprecate the [--cluster-zone flag](https://github.com/karmada-io/karmada/blob/276d6a8ad1f156546a3208aefb26ceb3252c3a7f/pkg/karmadactl/join/join.go#L131) of `join` and introduce a new flag `--cluster-zones`. (@whitewindmills, #3995)
- [x] Adopt `zones` in scheduler spread by constraints, possibly at [here](https://github.com/karmada-io/karmada/blob/276d6a8ad1f156546a3208aefb26ceb3252c3a7f/pkg/scheduler/core/spreadconstraint/group_clusters.go#L133-L161). (@zishen, #4002)
- [x] Adopt `zones` in scheduler filter, possibly at [here](https://github.com/karmada-io/karmada/blob/276d6a8ad1f156546a3208aefb26ceb3252c3a7f/pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go#L44-L46). (@whitewindmills, #3996)
- [x] Adopt `zones` in resource selector, possibly at [here](https://github.com/karmada-io/karmada/blob/276d6a8ad1f156546a3208aefb26ceb3252c3a7f/pkg/util/selector.go#L113-L116)  (@whitewindmills, #4010)

**Why is this needed**:

**Comment by whitewindmills** [comment]
> Adopt zones in scheduler spread by constraints

maybe we don't need this task because zone spread constraint has not been supported in the master branch. I'll consider `zones` fields in the new spread-constraint [pr](https://github.com/karmada-io/karmada/pull/3662).

**Comment by RainbowMango** [comment]
> Adopt zones in resource selector,

What about this one? 

> Adopt zones in scheduler filter

This one might be a challenge too.

**Comment by whitewindmills** [comment]
others look good to me.

**Comment by zishen** [comment]
I'm interested in this, too. How about I contribute `Add validation for zones` and `Transform potential zone to zones`?
@whitewindmills

**Comment by RainbowMango** [comment]
@zishen Please go for it.

**Comment by whitewindmills** [comment]
> Adopt zones in resource selector

I'm about to complete this task but have an ambiguous problem. For example, zones of cluster `member1` are `zone-a`,`zone-b`,`zone-c`.
1) I use such cluster affinity: `zone NotIn [zone-a zone-b]`, does cluster `member1` match it?
1) I use such cluster affinity: `zone In [zone-a zone-b]`, does cluster `member1` match it?

**Comment by RainbowMango** [comment]
That's a good question and I don't have a clue yet.
What's your opinion then?

**Comment by whitewindmills** [comment]
question 1 & 2 are both match cluster `member1`. only `zone NotIn [zone-a zone-b zone-c]` cannot match it. what do you think of this rule?

**Comment by RainbowMango** [comment]
My concern is that if the user wants to propagate a resource to a cluster that requires the cluster in a specific zone. 
For the example above, he/she requires a cluster in `zone-a`, if the scheduler selects `member1`, we can't guarantee the resource would be scheduled to the node in `zone-a`.  

Obviously, we need to do something about that. But before that, I'd like to take an exact match.

For your answers, I tend to Q1 and Q2 do not match.

**Comment by whitewindmills** [comment]
Maybe we can add a field to give the user the choice of whether to match exactly, For example:
```yaml
clusterAffinity:
  fieldSelector:
    matchExpressions:
    - key: zone
      operator: In
      values:
      - zone-a
      - zone-b
  zoneMatchBehavior: Exactly
```

**Comment by RainbowMango** [comment]
> Maybe we can add a field to give the user the choice of whether to match exactly,

Will see.  That's an option for the future.

**Comment by whitewindmills** [comment]
> Obviously, we need to do something about that. But before that, I'd like to take an exact match.

okay, let's implement it this way for now.

**Comment by RainbowMango** [comment]
Many thanks to @whitewindmills @zishen for the help, all tasks have been finished. 
/assign @whitewindmills @zishen 
/close
