### ISSUE TITLE
Cherrypick #3966: fix addAnnotationWithClusterName crash

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3968]
**Which PR needs cherry-picks:**

PR #3966 

**Which release branches need this patch:**
- [x] release-1.6 (@chaosi-zju, #3978)
- [x] release-1.5 (@chaosi-zju, #3977)
- [x] release-1.4 (@chaosi-zju, #3976)

**How to cherry-pick PRs:**

The `hack/cherry_pick_pull.sh` script can help you initiate a cherry-pick
automatically, please follow the instructions at [this guideline](https://karmada.io/docs/contributor/cherry-picks). 

The script will send the PR for you, please remember `copy the release notes` from
the original PR by to the new PR description part.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a **separate line**.

Then, the issue will be assigned to you.

**Useful References:**

- Release timeline: https://karmada.io/docs/releases
- How to cherry-pick PRs: https://karmada.io/docs/contributor/cherry-picks

**Anything else we need to know:**

**Comment by RainbowMango** [comment]
Thanks @chaosi-zju 
all tasks are now tracked by PRs(updated in issue description.)

/close
