### ISSUE TITLE
eliminate insecureSkipTLSVerify=true in karmada

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4024]
**What would you like to be added**:

`insecureSkipTLSVerify=true` means prohibit clientside from verifing the cert of serverside, this is an unsafe configuration, we can avoid unnecessary unsafe configurations.

- [x] 1. remove `insecureSkipTLSVerify` in YAML artifacts used by `deploy-karmada.sh`. (verification method: exec `hack/local-up-karmada.sh` success)  #4026
- [x] 2. remove `insecureSkipTLSVerify` in `karmadactl init`. (verification method: exec `karmadactl init` success). #4061
- [x] 3. remove `insecureSkipTLSVerify` in helm chart. (verification method: exec `helm install` success). #4033
- [x] 4. remove `insecureSkipTLSVerify` in test code. #4062
- [x] 5. remove `insecureSkipTLSVerify` in operator (verification method: install by operator success). #4063
~6. remove `insecureSkipTLSVerify` in `karmadactl register`. （just one line, can not be deleted）~

**Why is this needed**:

avoid unnecessary unsafe configurations.

**Comment by RainbowMango** [comment]
> remove insecureSkipTLSVerify in karmadactl register. （just one line, can not be deleted）

I guess you mean this piece of code:
https://github.com/karmada-io/karmada/blob/f2c7d0b80614816879d9fe734b334602ac9850f5/pkg/karmadactl/register/register.go#L839C6-L839C6

Why can not be removed?

**Comment by chaosi-zju** [comment]
https://github.com/karmada-io/karmada/blob/f2c7d0b80614816879d9fe734b334602ac9850f5/pkg/karmadactl/register/register.go#L835-L848

The corresponding code are building `kubeconfig` for member cluster to access Karmada, including：

1. member cluster use `token` to get `CA` from karmada-apiserver (one-way authentication, `InsecureSkipTLSVerify` flag in client is needed).
2. member cluster use `Bootstrap Token` to access karmada-apiserver to apply for assignment of `certificate` (two-way authentication, `CA` is need).
3. write `certificate` and `CA` into kubeconfig, then member cluster can access karmada-apiserver by this kubeconfig in following requests.

if remove `bootstrapConfig.Clusters[clustername].InsecureSkipTLSVerify = true` this line, then above step 1 will failed.

**Comment by RainbowMango** [comment]
Thanks for the clarification. 
/close
as all tasks has been resolved.
