### ISSUE TITLE
[umbrella] support promote dependent resources automatically

### ISSUE THREAD

**Issue by zhy76** [karmada-io/karmada#4036]
**What would you like to be added**:
Provide an automatic promotion mechanism for dependent resources in karmadactl. When promoting a resource, all the resources that it depends on will be automatically promoted as well. For example, promoting the Secret that is dependent by a Deployment.

**Why is this needed**:
Currently, karmadactl promote only support promote resources one by one, which is inconvenient.

**Related issue**:
#3842 #1862 

**Task Decomposition**:

- [ ] support promote native dependent resources automatically.
- [ ] support promote thirdparty dependent resources automatically.
- [ ] support promote CRD dependent resources automatically.
    - [ ] implement webhook interpreter adapter to get dependencies.
    - [ ] use configuration interpreter to get dependencies.
- [ ] E2E tests.
- [ ] Doc update. 

> Tips: Task splitting and details may change as features are developed.
