### ISSUE TITLE
[umbrella] sync replicas back to resource template if it is scaled in member cluster

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4057]
**What would you like to be added**:

Related task: #4053 

The GroupVersion of the `HorizontalPodAutoscaler` object being processed in the current issue is `autoscaling/v2`.

[The HorizontalPodAutoscaler autoscaling/v2 stable API moved to GA in kubernetes1.23. The HorizontalPodAutoscaler autoscaling/v2beta2 API has been deprecated.](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga)

**Why is this needed**:

Users can check the correct replica info of workload through resource templates.

Relevant meeting records:
https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#heading=h.ussp2ehaurbo

Task Decomposition:

- [x] HPA status aggregation. Aggregate the HPA status from different clusters onto the control plane HPA resource template using a resource interpreter, with the involved state field being `.status.currentReplicas`. @chaosi-zju #4064 
    - [x] Use `InterpreStatus` operation to collect status from resource in the member cluster to the work object. @chaosi-zju 
    - [x] Use `AggregateStatus` operation to collect status from binding status to resource template status. @chaosi-zju 
- [x] Add a controller, watch HPA objects, and write back `.status.currentReplicas` to the resource objects managed by HPA. @lxtywypc  #4072 
   (When dealing with resources associated with HPA, we can update the `scale` subresource of workload. In this way, modifiable resources can be extended to CRD resources.）
   (Note: This controller is disable by default, user can enable it with the [`--controllers` params of `karmada-controller-manager`](https://karmada.io/docs/next/administrator/configuration/configure-controllers/#configure-karmada-controllers))
- [x] By using the `retain` resource interpreter, prevent control-plane from modifying the replica of workload in the member cluster, and let the HPA controller in the member cluster modify it. It will be tracked by #4058
- [x] use status.DesiredReplicas instead of status.CurrentReplicas of HPA to update resource scale #4082
- [x] sync deployment replicas when it is controlled by hpa #4707
- [x] Add E2E case to cover this case. #4136 #4716

**Comment by lxtywypc** [comment]
I'll be glad to help do some parts if you need. :)

**Comment by XiShanYongYe-Chang** [comment]
Hi @lxtywypc, thanks a lot 👍

**Comment by XiShanYongYe-Chang** [comment]
Which one do you want to do? I will add you to the corresponding task item.

**Comment by chaosi-zju** [comment]
I want to pick first two tasks~

**Comment by XiShanYongYe-Chang** [comment]
> I want to pick first two tasks~

Ok, thanks~

**Comment by lxtywypc** [comment]
Then I can help add the controller and fill the retain interpreter for deployment :)

**Comment by XiShanYongYe-Chang** [comment]
> Then I can help add the controller and fill the retain interpreter for deployment :)

Thanks a lot, @lxtywypc, I have assigned the task of adding a new controller to you.

**Comment by RainbowMango** [comment]
After quickly going through #4072, seems it is beyond the scope of the task that `a controller takes responsibility for syncing replicas from HPA to the resource template`.

**Comment by lxtywypc** [comment]
Hi @RainbowMango  

I am a little confused. Could you please explain with more details about what we hope to do if we shouldn't sync the replicas from HPA to the origin resource in fed-control-plane?

**Comment by RainbowMango** [comment]
My understanding of this task is that we need `a controller` that syncs replicas from HPA to resource template.
Seems #4072 includes changes that have not been listed above, such as webhook thing.

https://github.com/karmada-io/karmada/pull/4072#issuecomment-1724797967 explains my concerning about the webhook approach.

**Comment by lxtywypc** [comment]
Okay I got it. I will give a try to adjust it.  

Thanks for your explanation~:)

**Comment by XiShanYongYe-Chang** [comment]
> Add a controller, watch HPA objects, and write back .status.currentReplicas to the resource objects managed by HPA.

Is it more reasonable to use `currentReplicas` or `desiredReplicas`, as discussed earlier here:

https://github.com/karmada-io/karmada/pull/4072#discussion_r1331376846

We can continue the discussion here and finally reach an agreement.

/cc @lxtywypc @chaunceyjiang @RainbowMango @chaosi-zju

**Comment by XiShanYongYe-Chang** [comment]
I agree to use `desiredReplicas`.

First, this is consistent with the behavior of a single cluster. 
When the repliccas of deployment is adjusted, the expected value(.spec.replicas) is adjusted immediately. Then, the deployment-controller adjusts the value to make the actual situation gradually approach the target and finally achieve the target. This will be a dynamic adjustment process.
For example, the kubectl get result can be `5/7` -> `6/7` ->`7/7`. But when we use `currentReplicas`, the result will be `5/5` -> `6/6` -> `7/7`.

Second, when the cluster cannot provide sufficient replicas due to insufficient resources, use `desiredReplicas` to help users quickly identify problems.
For example, the kubectl get result can be `5/7` -> `6/7`, when we use `currentReplicas`, the result will be `5/5` -> `6/6`.

**Comment by lxtywypc** [comment]
Hi @RainbowMango @chaosi-zju @XiShanYongYe-Chang @chaunceyjiang  I'm sorry for replying late.  

In my opinion, I prefer to use `CurrentReplicas`.  

Following the code of the `HPA Controller`, we find that the `CurrentReplicas` is the actual value of `Scale.spec.replicas`, but not the actual number of created pods:  

https://github.com/kubernetes/kubernetes/blob/v1.27.3/pkg/controller/podautoscaler/horizontal.go#L798  

It quite might be a little hysteresis, but it is exact. The `DesiredReplicas` is the best result we hope to reach, but I think we still should consider about the circumastance that the actual `Scale` does not match the `Desired`.

**Comment by chaunceyjiang** [comment]
Hi, @lxtywypc 
To be honest, I didn't understand what you meant. I think the core code of HPA controller should be this.

https://github.com/kubernetes/kubernetes/blob/v1.27.3/pkg/controller/podautoscaler/horizontal.go#L876-L878

**Comment by lxtywypc** [comment]
Yes, this part tries to update scale with calculated `DesiredReplicas`. 

What I mean is that the `CurrentReplicas` is also the `.spec.replicas`, and it is trustable. Even it is with low probability, we should still consider about the `Scale.spec.replicas` does not match the `DesiredReplicas ` cause by various potential reason.

**Comment by XiShanYongYe-Chang** [comment]
When I use DesiredReplicas, the test result is:

Get deploy on the member cluster:
![image](https://github.com/karmada-io/karmada/assets/78244870/835a9ac3-a992-404e-a4df-bc42a4f8a130)

Get deploy on the karmada control-plane:
![image](https://github.com/karmada-io/karmada/assets/78244870/7d4dbf19-85e2-4feb-bc68-b32bcf3de549)

So, I prefer to select DesiredReplicas.
/cc @chaunceyjiang @lxtywypc @RainbowMango @chaosi-zju

**Comment by lxtywypc** [comment]
Okay, then I will do it as soon as possible.

**Comment by RainbowMango** [comment]
ping @XiShanYongYe-Chang to check the task status.
Moved this to milestone to v1.11.

**Comment by XiShanYongYe-Chang** [comment]
All subtasks have been finished, let me close it.
/close
