### ISSUE TITLE
[umbrella] Auto detect whether workload needs to retain replicas in the member cluster through Retain operation

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4058]
**What would you like to be added**:

Add the `Retain` operation for workload resources, when there are relevant HPAs in effect, and keep the number of replicas in the member cluster.

**Why is this needed**:

When users propagate workload resources (such as Deployment) and HPA to member clusters through Kamada, the HPA controller in the member cluster will work and dynamically adjust the scale subresource of the workload. At the same time, Karmada control plane will also attempt to modify the replicas on the workload in the member cluster. These two operations will conflict. We need to retain the modification of replicas on workload by the HPA controller in the member cluster.

**It can be divided into the following tasks.**

- [x] Add a specific label to the workload resource to indicate its association with working HPAs. #4078
- [x] Add retain operation in native resourceinterpreter for Deployment resource. #4078
- [x] Set the retain operation more common and not limited to the deployment resource. 
       Ref task discussion: https://github.com/karmada-io/karmada/pull/4078#discussion_r1332455732
- [x] Add E2E to cover this case. #4764

**Comment by chaunceyjiang** [comment]
Hi @XiShanYongYe-Chang, has anyone picked up this issue yet? If not, i can pick up this one.

**Comment by XiShanYongYe-Chang** [comment]
> Hi @XiShanYongYe-Chang, has anyone picked up this issue yet? If not, i can pick up this one.

Thanks a lot~, I will assign it to you.
/assign @chaunceyjiang

**Comment by chaosi-zju** [comment]
@chaunceyjiang hello, have you start your task? I am doing another task (#4057), however, I cannot test my code without the feature `Add retain operation in native resourceinterpreter for Deployment resource`, then my code may be imcomplete to merge, so, I wanna if you didn't start this subtask, may I do this subtask?

**Comment by RainbowMango** [comment]
ping @XiShanYongYe-Chang to sync the status.

**Comment by XiShanYongYe-Chang** [comment]
All sub-tasks have been finished. Let me close it.
/close
