### ISSUE TITLE
Set MinVersion to VersionTLS13 for tlsconfig to fix CVE-2016-2183

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#4191]
**What would you like to be added**:
set MinVersion to VersionTLS13 for tlsconfig to fix [CVE-2016-2183](https://github.com/advisories/GHSA-w2rw-pv8p-h9c8). Through nmap scanning, the following components were found to have this vulnerability. 
- karmada-apiserver
- karmada-aggregated-apiserver
- karmada-search
- karmada-metrics-adapter
- etcd

Referring to [Installation overview](https://karmada.io/docs/installation/), there are four installation methods. So, this issue will also be divided into four parts to solve.
- [x] Installation from Source  (@zhzhuang-zju)
   - [x] karmada-apiserver (@zhzhuang-zju, #4198)
   - [x] karmada-aggregated-apiserver (@zhzhuang-zju, #4198)
   - [x] karmada-search (@zhzhuang-zju, #4198)
   - [x] karmada-metrics-adapter (@zhzhuang-zju, #4198)
   - [x] etcd (@zhzhuang-zju, #4253)
- [x] Installation of CLI Tools
   - [x] karmada-apiserver  (@yanfeng1992, #4181)
   - [x] karmada-aggregated-apiserver (@yanfeng1992, #4181)
   - [x] karmada-search (@yanfeng1992, #4193)
   - [x] karmada-metrics-adapter (@yanfeng1992, #4193)
   - [x] etcd (@zhzhuang-zju, #4253)
- [x] Install Karmada by Helm Chart Deployment
   - [x] karmada-apiserver (@zhzhuang-zju, #4198)
   - [x] karmada-aggregated-apiserver (@zhzhuang-zju, #4198)
   - [x] karmada-search (@zhzhuang-zju, #4198)
   - [x] karmada-metrics-adapter (not involving)
   - [x] etcd (@zhzhuang-zju, #4253)
- [x] Install Karmada by Karmada Operator
   - [x] karmada-apiserver (@zhzhuang-zju, #4198)
   - [x] karmada-aggregated-apiserver (@zhzhuang-zju, #4198)
   - [x] karmada-search (not involving)
   - [x] karmada-metrics-adapter (@zhzhuang-zju, #4198)
   - [x] etcd (@zhzhuang-zju, #4253)
- [x] File a [security advisory](https://github.com/karmada-io/karmada/security/advisories) or a document for this CVE
 
**Why is this needed**:
to fix [CVE-2016-2183](https://github.com/advisories/GHSA-w2rw-pv8p-h9c8)

**Comment by zhzhuang-zju** [comment]
@yanfeng1992 Hello~, I found that you have solved the vulnerabilities of ```karmada-apiserver``` and ```karmada-aggregated-apiserver``` in the second installation method in PR #4181. If you are interested in completing some of the tasks, please let me know, thank you~

**Comment by RainbowMango** [comment]
Good Job @zhzhuang-zju !
I added another task for security advisory or documents to the end of the list.

/help

**Comment by zhzhuang-zju** [comment]
When setting minVersion to ```VersionTLS13``` for tlsconfig in ```etcd```, ```karmada-apiserver``` will restart repeatedly.
How to reproduce it?
1.Launch Karmada with ```hack/local-up-karmada.sh```.
2.set ```- --tls-min-version=TLS1.3``` with ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-host edit sts etcd -nkarmada-system -oyaml```.
```bash
➜  bin kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-host edit sts etcd -nkarmada-system -oyaml
        - --key-file=/etc/karmada/pki/etcd-server.key
        - --trusted-ca-file=/etc/karmada/pki/etcd-ca.crt
        - --data-dir=/var/lib/etcd
        - --snapshot-count=10000
        - --tls-min-version=TLS1.3
```
3.```karmada-apiserver``` restarts repeatedly.
```bash
➜  bin kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-host get po -A -w|grep karmada-apiserver 
karmada-system       karmada-apiserver-7458585787-pfqjp                     0/1     Running            3 (35s ago)     19h
karmada-system       karmada-apiserver-7458585787-pfqjp                     0/1     Error              3 (40s ago)     19h
karmada-system       karmada-apiserver-7458585787-pfqjp                     0/1     CrashLoopBackOff   3 (5s ago)      19h
karmada-system       karmada-apiserver-7458585787-pfqjp                     0/1     Running            4 (22s ago)     19h
karmada-system       karmada-apiserver-7458585787-pfqjp                     0/1     Error              4 (42s ago)     19h
karmada-system       karmada-apiserver-7458585787-pfqjp                     0/1     CrashLoopBackOff   4 (4s ago)      19h
```
4.Executing ```kubectl describe pod``` will get the following results.
```bash
➜  bin kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-host describe po karmada-apiserver-7458585787-pfqjp -nkarmada-system
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  4m48s (x8 over 5m58s)  kubelet  Liveness probe failed: HTTP probe failed with statuscode: 500
  Normal   Killing    4m48s                  kubelet  Container karmada-apiserver failed liveness probe, will be restarted
  Warning  Unhealthy  4m44s (x17 over 19h)   kubelet  Readiness probe failed: HTTP probe failed with statuscode: 500
  Warning  BackOff    46s (x11 over 3m35s)   kubelet  Back-off restarting failed container karmada-apiserver in pod karmada-apiserver-7458585787-pfqjp_karmada-system(1f129eb7-bf4e-417d-9f17-9b9952da4530)
```
5.Executing ```kubectl logs -f``` will get the following results.
```bash
➜  bin kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-host logs -f karmada-apiserver-7458585787-pfqjp -nkarmada-system 
W1101 07:02:10.211878       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": "etcd-client.karmada-system.svc.cluster.local:2379",
  "ServerName": "etcd-client.karmada-system.svc.cluster.local",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: authentication handshake failed: remote error: tls: protocol version not supported"
```

**Comment by zhzhuang-zju** [comment]
In contrast, everything works fine when set ```--cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA``` in ```etcd```. This ```ciphersuites``` is obtained by using ```nmap``` to scan out the ```ciphersuites``` used by ```etcd``` and removing its insecure algorithms.

**Comment by RainbowMango** [comment]
Seems there is a conclusion that etcd v3.5 does not support TLS1.3. See [the discussion in etcd community](https://github.com/etcd-io/etcd/issues/13506#issuecomment-979915696). 

Can you help to set the tls-max-version and try again as per https://github.com/etcd-io/etcd/issues/13506#issuecomment-1678011069 ?

If it not work, please try with etcd v3.5.10(the latest release by now)

**Comment by yanfeng1992** [comment]
Try this configuration to see if it can avoid restarting

--cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA  

or 

--cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384


https://juejin.cn/post/7202510819429843000 @zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
> Try this configuration to see if it can avoid restarting
> 
> --cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA
> 
> or
> 
> --cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
> 
> https://juejin.cn/post/7202510819429843000 @zhzhuang-zju

Thank you for the solution you provided, it does work! But we hope to limit the minimum version of ```tls``` to 1.3 so that we don't have to maintain ```cipher-suites```.

**Comment by zhzhuang-zju** [comment]
> Seems there is a conclusion that etcd v3.5 does not support TLS1.3. See [the discussion in etcd community](https://github.com/etcd-io/etcd/issues/13506#issuecomment-979915696).
> 
> Can you help to set the tls-max-version and try again as per [etcd-io/etcd#13506 (comment)](https://github.com/etcd-io/etcd/issues/13506#issuecomment-1678011069) ?
>
 set ```tls-max-version``` and ```tls-min-version```, ```karmada-spiserver``` still restarts repeatedly.
> If it not work, please try with etcd v3.5.10(the latest release by now)
Changing release of etcd to v3,5,10, the status of etcd will change to ```ErrImagePull```.
```bash
  Normal   Pulling    16m (x4 over 17m)     kubelet            Pulling image "registry.k8s.io/etcd:3.5.10"
  Warning  Failed     16m (x4 over 17m)     kubelet            Failed to pull image "registry.k8s.io/etcd:3.5.10": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/etcd:3.5.10": failed to resolve reference "registry.k8s.io/etcd:3.5.10": registry.k8s.io/etcd:3.5.10: not found
  Warning  Failed     16m (x4 over 17m)     kubelet            Error: ErrImagePull
  Warning  Failed     15m (x6 over 17m)     kubelet            Error: ImagePullBackOff
  Normal   BackOff    2m38s (x64 over 17m)  kubelet            Back-off pulling image "registry.k8s.io/etcd:3.5.10"
```

**Comment by zhzhuang-zju** [comment]
> Seems there is a conclusion that etcd v3.5 does not support TLS1.3. See [the discussion in etcd community](https://github.com/etcd-io/etcd/issues/13506#issuecomment-979915696).
> 
> Can you help to set the tls-max-version and try again as per [etcd-io/etcd#13506 (comment)](https://github.com/etcd-io/etcd/issues/13506#issuecomment-1678011069) ?
> 
> If it not work, please try with etcd v3.5.10(the latest release by now)

When upgrading etcd to v3.5.10 with ```gcr.io/etcd-development/etcd:v3.5.10```, the restart problem still exists.
```bash
➜  karmada git:(tls1.3) ✗ kh get po -w -A |grep karmada-apiserver
karmada-system       karmada-apiserver-5cb5b97b96-8rfkk                     0/1     CrashLoopBackOff   20 (4m24s ago)   2d
```

**Comment by zhzhuang-zju** [comment]
Referring to https://github.com/etcd-io/etcd/discussions/16894, ```kube-apiserver``` can only support ```tls1.2``` when connecting to etcd, unless kube-apiserver is upgraded to 1.28.0. So, we cannot fix CVE-2016-2183 simply by setting ```tls-min-verison``` to ```TLS1.3```. I prefer to use golang's default secure cipher suites as etcd's cipher suites. Like
```yaml
...
- --cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM
_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_E
CDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY130
5_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
...
```
The nmap scan results are as follows
```bash
# nmap -sV  --script ssl-enum-ciphers -p 2379 10.244.0.26 
Starting Nmap 7.80 ( https://nmap.org ) at 2023-11-15 07:39 UTC 
Nmap scan report for 10-244-0-26.etcd-client.karmada-system.svc.cluster.local (10.244.0.26) 
Host is up (0.000055s latency).


PORT     STATE SERVICE          VERSION
PORT     STATE SERVICE          VERSION
2379/tcp open  ssl/etcd-client?
2379/tcp open  ssl/etcd-client?
| ssl-enum-ciphers:
| ssl-enum-ciphers:
|   TLSv1.2:
|   TLSv1.2:
|     ciphers:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|     cipher preference: server
|_  least strength: A

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 11.73 seconds

```
cc @RainbowMango @yanfeng1992

**Comment by RainbowMango** [comment]
> I prefer to use golang's default secure cipher suites as etcd's cipher suites.

+1

**Comment by yanfeng1992** [comment]
> > I prefer to use golang's default secure cipher suites as etcd's cipher suites.
> 
> +1

I have some different opinions. Can I only support cipher suites of tls1.3?
Can you help me try the configuration? @zhzhuang-zju 
- --cipher-suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256

I don’t think it’s necessary to support so many cipher-suites. The fewer supported, the smaller the risk. @RainbowMango

**Comment by zhzhuang-zju** [comment]
> > > I prefer to use golang's default secure cipher suites as etcd's cipher suites.
> > 
> > 
> > +1
> 
> I have some different opinions. I don’t think it’s necessary to support so many cipher-suites. The fewer supported, the smaller the risk. @RainbowMango
> 
> I think we can refer to the configuration of other projects [openshift/cluster-etcd-operator#970](https://github.com/openshift/cluster-etcd-operator/pull/970)

Thanks for your opinions~. In fact, we only need to remove the unsafe algorithms in the cipher suites to fix [CVE-2016-2183](https://github.com/advisories/GHSA-w2rw-pv8p-h9c8),  and the question is which algorithms that belong to ```tls1.2``` do we need to retain. I haven’t found the relevant official answer yet, so I chose golang's default secure cipher suites as etcd's cipher suites. Do you have any other suggestions or can you find an official solution? If so, please let me know~

**Comment by RainbowMango** [comment]
> I have some different opinions. I don’t think it’s necessary to support so many cipher-suites. The fewer supported, the smaller the risk. @RainbowMango

We need to balance security and reliability. I agree that a short cipher list may be safer, but it's hard to guarantee it works with wide kube-apiserver versions. I don't think we have to do such testing against many versions of kube-apiserver, because it's beyond our original intention. In addition, we can't guarantee the behavior of the following kube-apiserver.

But if there is a need, we can always shorten the list.

Does that make sense to you? @yanfeng1992

**Comment by yanfeng1992** [comment]
> We need to balance security and reliability. I agree that a short cipher list may be safer, but it's hard to guarantee it works with wide kube-apiserver versions. I don't think we have to do such testing against many versions of kube-apiserver, because it's beyond our original intention. In addition, we can't guarantee the behavior of the following kube-apiserver.

There is no special reason. Our current environment refers to this configuration, so it is recommended to use this configuration. Because we can configure the kube-apiserver version, and the community uses golang's default configuration, I think it is OK.

@RainbowMango @zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
> * [ ]  File a [security advisory](https://github.com/karmada-io/karmada/security/advisories) or a document for this CVE

I filed a draft security advisory for this CVE on my private repo. Until it is published, this draft security advisory will only be visible to me, so I will show it with pictures, it looks like:
![image](https://github.com/karmada-io/karmada/assets/81208264/407e85f5-d24f-4413-8f70-c846ba7819ed)

What have to be aware of is once published, gitHub may use this advisory to send [Dependabot alerts](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts#dependabot-alerts-for-vulnerable-dependencies) to affected repositories and redistribute the advisory through its [API](https://docs.github.com/v4/object/securityadvisory/) and [Atom feed](https://docs.github.com/v3/activity/feeds/). This may cause trouble for the repository that references our code.
cc @RainbowMango @yanfeng1992

**Comment by zhzhuang-zju** [comment]
![image](https://github.com/karmada-io/karmada/assets/81208264/8b3f9713-92d0-4244-9390-c3610c4a7e79)
I rewrote the secutity advisory draft，referring to https://github.com/zhzhuang-zju/karmada/security/advisories/GHSA-jj46-2p6m-6hcj. cc @RainbowMango @yanfeng1992

**Comment by RainbowMango** [comment]
See the advisor: https://github.com/karmada-io/karmada/security/advisories/GHSA-7xg2-83f8-39mr
@zhzhuang-zju

**Comment by RainbowMango** [comment]
/close
As all tasks have been finished.
