### ISSUE TITLE
[umbrella] Add Implementation for Service discovery with native Kubernetes naming and resolution

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4292]
**What would you like to be added**:
In https://github.com/karmada-io/karmada/pull/4287, we propose a way to implement service discovery with native Kubernetes naming and resolution.

The specific work items are as follows:

release-1.8(1130)
- [ ] Add proposal for ` service discovery with native Kubernetes naming and resolution` - https://github.com/karmada-io/karmada/pull/4287
- [ ] Add corresponding API - https://github.com/karmada-io/karmada/pull/4290 
- [ ] For mcs-controller, List&watch mcs and service, reconcile the work in execution namespace @Rains6 
- [ ] For mcs-eps-controller, List&watch mcs, collect the corresponding EndpointSlice from `ServerLocations` and create/update the corresponding Work. @jwcesign 

release-1.9(1215)
- [ ] For mcs-controller, List&watch cluster creation/deletion, reconcile the work in corresponding cluster execution namespace.
- [ ] For mcs-eps-controller, List&watch cluster creation/deletion, reconcile the EndpointSlice's work in corresponding cluster execution namespace.
- [ ] If cluster gets unhealth, mcs-eps-controller should delete the EndpointSlice from all the cluster execution namespace. 

**Why is this needed**:

Ref proposal https://github.com/karmada-io/karmada/pull/4287

Help

Anyone who wants to participate in one of the tasks can come and assign the tasks. Feel free to let me know in the comments and I will mark it after the corresponding task item, thanks~

/help

**Comment by jwcesign** [comment]
Now, the EPS synchronization logic is as follows:
![image](https://github.com/karmada-io/karmada/assets/19745536/3b071db4-6ada-44e1-9d41-48c1dcd8624e)

1.List&watch mcs, build informer to list&watch the eps in `ServiceProvisionClusters`
2.List&watch eps in ServiceProvisionClusters
3.create the corresponding work, the name rule is: `mcs-{endpointslice name}-{hash}`
4.Sync the endpointslice's work in step 3 to `ServiceConsumptionClusters`, the endpoint slice name will be changed to `{source-cluster-name}-{endpointslcie-name}`
5.The work will trigger to create the endpointslice int `ServiceConsumptionClusters`.

**Comment by Affan-7** [comment]
Hi @jwcesign, can you please assign me something to work on?
