### ISSUE TITLE
[umbrella] Add FleetAPIServer, providing a unified view of resources across multiple clusters

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4319]
**What would you like to be added**:

Providing a unified view of resources across multiple clusters.

**Why is this needed**:

For specific details, please refer to #4317.

The specific work items can be planned as follows:

- [ ] Add FleetAPIServer as an independent component.
  - [ ] After forking the Kubernetes repository, perform feature pruning and disable unnecessary APIs.
  - [ ] Import the Kubernetes fork repository to achieve integration between the Kubernetes vanilla API and Karmada Fleet API.
  - [ ] Deploy FleetAPIServer
    - [ ] Build and deploy the FleetAPIServer component, set the storage key prefix for etcd.
- [ ] FleetAPIServer support Cluster
  - [ ] Deployment APIService, install Cluster resource with `karmada-aggregator`
  - [ ] adoption of `karmadactl`
    - [ ] join/join
    - [ ] other command 
  - [ ] deploy `fleet-controller`
- [ ] Synchronize Cluster resources from FleetAPIServer to karmada-apiserver
  - [ ] Set the FleetAPIServer etcd key prefix to be the same as the karmada-apiserver etcd key prefix (default value is /registry), and confirm through testing that Cluster data can be shared.
  - [ ] Test Karmada's existing logic processing is normal.
- [ ] Increase enabling federated functionality.
  - [ ] Enable Karmada
  - [ ] Establish Karmada authentication channel.
- [ ] Implementing Karmada Fleet API
  - [ ] Add handling of the clusterspaces parameter in the request path processing to obtain the target cluster.
  - [ ] Resource Name Processing
    - [ ] Resource name lookup path: url -> query parameters -> body, return if found.
    - [ ] Compare the cluster information specified by clusterspaces from the URL, and handle errors if there are inconsistencies.
  - [ ] When the cluster is a specific cluster
    - [ ] Determine if the cluster information is valid.
    - [ ] Build cluster authentication information based on the cluster name, forward user requests to the target cluster, and return the request results.
  - [ ] When the cluster is karmada.
    - [ ] Build Karmada control plane authentication information, forward the request to karmada-apiserver, and return the request result.
  - [ ] When the cluster is all.
    - [ ] Traverse all clusters (including Karmada) and forward requests.
      - [ ] During the traversal process, it is necessary to verify whether the API belonging to the requested resource is installed in this cluster.
    - [ ] Anonymize the name of the resource returned in the request, and the processing format is `xx.clusterspace.yy`.
    - [ ] Aggregate the returned results.
    - [ ] If the watch is specified as true in the list operation, it is necessary to aggregate the watch streams of different clusters.
    - [ ] Aggregation processing of resourceVersion.
    - [ ] handle list continue
- [ ] Implementing Kubernetes vanilla API
  - [ ] Parse cluster information from resource names and redirect requests to the Karmada Fleet API.
- [ ] Test
- [ ] Document
 
Node: Task decomposition will be updated in a timely manner as the subsequent development progresses.
