### ISSUE TITLE
[umbrella] Enable golangci-lint(revive) to improve code quality

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4490]
**What would you like to be added**:

Enable the appropriate revive check rules to improve PR quality.

**Why is this needed**:

For golangci-lint (revive), in the absence of any specific configuration, default checking rules will be applied as reference:
https://github.com/golangci/golangci-lint/blob/0264eaa5c7851a35883e2f462e66d648ab8598df/pkg/golinters/revive.go#L251

In PR https://github.com/karmada-io/karmada/pull/3567, a single rule is configured as shown in the image:

 ![image](https://github.com/karmada-io/karmada/assets/19745536/1e0edccd-2207-4c2a-a2af-f9817ca7fdba). 

This configuration results in only this rule being used and disables checking for other rules.

Thus, it's advisable to activate the default rules and rectify the associated warnings(You can pick one or multiple):

- [x] VarDeclarations @jwcesign, https://github.com/karmada-io/karmada/pull/4492
- [x] PackageComments @zhzhuang-zju, https://github.com/karmada-io/karmada/pull/4503
- [x] DotImports @zhzhuang-zju, https://github.com/karmada-io/karmada/pull/4504
- [x] BlankImports @jwcesign, https://github.com/karmada-io/karmada/pull/4495
- [x] Exported @jwcesign, https://github.com/karmada-io/karmada/pull/4491
- [x] VarNaming @jwcesign, https://github.com/karmada-io/karmada/pull/4496
- [x] IndentErrorFlow @jwcesign, https://github.com/karmada-io/karmada/pull/4495
- [x] Range @Larry-shuo, https://github.com/karmada-io/karmada/pull/4511
- [x] Errorf @zhzhuang-zju, https://github.com/karmada-io/karmada/pull/4504
- [x] ErrorNaming @Larry-shuo, https://github.com/karmada-io/karmada/pull/4511
- [x] ErrorStrings @chaosi-zju, https://github.com/karmada-io/karmada/pull/4498
- [x] ReceiverNaming @chaosi-zju, https://github.com/karmada-io/karmada/pull/4499
- [x] IncrementDecrement @chaosi-zju, https://github.com/karmada-io/karmada/pull/4501
- [x] ErrorReturn @chaosi-zju, https://github.com/karmada-io/karmada/pull/4502
- [x] UnexportedReturn @XiShanYongYe-Chang https://github.com/karmada-io/karmada/pull/4552
- [ ] TimeNaming @sagnik3788 
- [x] ContextKeysType @XiShanYongYe-Chang https://github.com/karmada-io/karmada/pull/4552
- [x] ContextAsArgument @XiShanYongYe-Chang https://github.com/karmada-io/karmada/pull/4552
- [ ] EmptyBlock @sagnik3788 
- [x] SuperfluousElse @liangyuanpeng, https://github.com/karmada-io/karmada/pull/4493
- [x] UnusedParam @Affan-7  https://github.com/karmada-io/karmada/pull/4512
- [x] UnreachableCode @Affan-7 https://github.com/karmada-io/karmada/pull/4514
- [x] RedefinesBuiltinID @Affan-7 https://github.com/karmada-io/karmada/pull/4513

Check out the rule details here: https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#if-return
You can update this link: https://github.com/karmada-io/karmada/blob/c218f93ce3fe6a626f37b09b418e687d4bf9b41e/.golangci.yml#L67, then run `hack/verify-staticcheck.sh` to view the related warning.

Node: Task decomposition will be updated in a timely manner as the subsequent development progresses.

**Comment by zhzhuang-zju** [comment]
@Affan-7 Hi~Are you interested in getting involved?

**Comment by Affan-7** [comment]
Thanks @zhzhuang-zju

I would love to work on this.

**Comment by jwcesign** [comment]
Hi, @Affan-7 Thanks.
Which one would you like to work on? I can assign to you.

**Comment by liangyuanpeng** [comment]
I will take the `SuperfluousElse`, assign to me please,Thanks.

**Comment by zhzhuang-zju** [comment]
I will take the `PackageComments` and `DotImports`, assign to me please,Thanks. BTW, if necessary, you can also assign other tasks to me.

**Comment by chaosi-zju** [comment]
* ErrorStrings #4498

**Comment by Larry-shuo** [comment]
I want to try this issue, can I take some tasks? THX!

**Comment by zhzhuang-zju** [comment]
> I want to try this issue, can I take some tasks? THX!

Of course, very welcome~ You can choose to implement the task assigned to @jwcesign above but which has not yet implemented PR. It would be better if you could tell us the tasks you selected, so as to avoid duplication of operations.

**Comment by Larry-shuo** [comment]
I will take `Range` and `ErrorNaming`, assign to me please, Thanks.

**Comment by zhzhuang-zju** [comment]
> I will take `Range` and `ErrorNaming`, assign to me please, Thanks.

Okay, you can start it first, and we will modify the task information later~

**Comment by sagnik3788** [comment]
can i  take the `TimeNaming` and  `EmptyBlock `,  Thanks.

**Comment by jwcesign** [comment]
> can i take the TimeNaming and EmptyBlock , Thanks.

Hi, @XiShanYongYe-Chang Is that ok for you?

**Comment by XiShanYongYe-Chang** [comment]
> Hi, @XiShanYongYe-Chang Is that ok for you?

Offcrouse~.

**Comment by XiShanYongYe-Chang** [comment]
Kindly ping @sagnik3788

**Comment by Affan-7** [comment]
Dear contributors,

Please assign me some more issues. I would love to work on the Karmada.

**Comment by Affan-7** [comment]
I think we should implement a `triage/accepted` label. It would help new contributors a lot.

**Comment by RainbowMango** [comment]
> I think we should implement a `triage/accepted` label. It would help new contributors a lot.

How does it help? Do we need to upgrade prow?

**Comment by Affan-7** [comment]
>How does it help? Do we need to upgrade prow?

It would help new contributors to work on things that matter. It will avoid time wasted on something that the community doesn't needs. A new contributor will avoid issues that don't have `traige/accepted` label.

I think we don't need to upgrade the prow, we just need these labels added to the Karmada repo like Kubernetes.

https://github.com/kubernetes/website/labels?q=triage

**Comment by RainbowMango** [comment]
Thanks @Affan-7 I found this guide for traige: https://www.kubernetes.dev/docs/guide/issue-triage/
I don't know if we need this for now. I will look into it further.

**Comment by RainbowMango** [comment]
@sagnik3788 @jwcesign 
Given no response from @sagnik3788, I finished the left two tasks at #4568 during the update of golangci-lint. 
But still thanks to @sagnik3788.
