### ISSUE TITLE
[umbrella] enhance scheduler-estimator

### ISSUE THREAD

**Issue by wengyao04** [karmada-io/karmada#4578]
**What would you like to be added**:

- [ ] Add e2e test for scheduler accurate estimator. Why is it hard to add e2e test for accurate estimator ? In order to resolve the resource fragmentation issue, Karmada supports two options: 1) Resource Model (details are [here](https://github.com/karmada-io/karmada/blob/master/pkg/estimator/client/general.go#L74-L85)) 2) accurate estimator which is a grpc sever list/watch all nodes of the managed cluster. People usually choose one of them, and don't use them together. It is a bit hard to use the current e2e test setup to test both options. Could we set up another e2e test to test accurate estimator ?
- [ ] Add resource quota estimator plugin document. We have a chapter about [scheduler estimator](https://karmada.io/docs/userguide/scheduling/scheduler-estimator/), let's add a chapter to introduce resource quota estimator plugin.
- [ ] When design resource quota estimator plugin, we add `namespace` field in`workv1alpha2.ReplicaRequirements`. But `namespace` is already in `ObjectReference`, we add it because we also need namespace in the [resource interpreter](https://github.com/karmada-io/karmada/blob/master/pkg/resourceinterpreter/interpreter.go#L46-L47).
If we don't include `namespace` in `workv1alpha2.ReplicaRequirements`, we have to change interface to return `namespace` and this change is not backward compatible. We can think about how to decouple resource interpreter interface from `ResourceBinding`
- [ ] Restructure [estimateReplicas](https://github.com/karmada-io/karmada/blob/master/pkg/estimator/server/estimate.go#L59-L96) and make it as the default node source replica estimator plugin (we discussed in [here](https://github.com/karmada-io/karmada/pull/4534#discussion_r1455781778)).

**Why is this needed**:

**Comment by AadityaLamichhane** [comment]
Hello, I am going through the the discussion. Is it being worked on ? can I work on this  ?

**Comment by zhzhuang-zju** [comment]
Thanks @AadityaLamichhane for your active contributions. Some tasks listed in this issue are completed, while others are outdated. I'll update the details to help you choose accordingly.

- [x] Add e2e test for scheduler accurate estimator. This task is completed, see #7117
- [ ]  Add resource quota estimator plugin document. This is a pending task.
- [x] When design resource quota estimator plugin, we add namespace field inworkv1alpha2.ReplicaRequirements. But namespace is already in ObjectReference, we add it because we also need namespace in the [resource interpreter](https://github.com/karmada-io/karmada/blob/master/pkg/resourceinterpreter/interpreter.go#L46-L47). Not required for now.
- [x] Restructure [estimateReplicas](https://github.com/karmada-io/karmada/blob/master/pkg/estimator/server/estimate.go#L59-L96) and make it as the default node source replica estimator plugin. This task is completed, see https://github.com/karmada-io/karmada/pull/6877
