### ISSUE TITLE
Cleanup cyclomatic complexity issue

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#460]
**What would you like to be added**:
There are 4 functions in which cyclomatic complexity exceed 15:
- [x] 1. EnsureWork() with complexity 21: (@XiShanYongYe-Chang #473)
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/util/helper/binding.go#L154
- [x] 2. retainServiceFields() with complexity 20: (@XiShanYongYe-Chang #476 )
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/util/helper/binding.go#L154
- [x] 3. getScheduleType() with complexity 20: (@ESonata #685)
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/scheduler/scheduler.go#L323
- [x] 4. RunJoin() with complexity (@XiShanYongYe-Chang #636 )
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/karmadactl/join.go#L154

You can get the complexity on your side by following commands:
```
# go get github.com/fzipp/gocyclo/cmd/gocyclo@latest
# gocyclo -over 15 pkg
21 helper EnsureWork pkg/util/helper/binding.go:154:1
20 objectwatcher retainServiceFields pkg/util/objectwatcher/retain.go:61:1
20 scheduler (*Scheduler).getScheduleType pkg/scheduler/scheduler.go:323:1
18 karmadactl RunJoin pkg/karmadactl/join.go:154:1
```

I'd prefer to fix it by separated PRs(each PR fix one issue), forks can choose any issues.

**Why is this needed**:
A function with a higher cyclomatic complexity requires more test cases to cover all possible paths and is potentially harder to understand.

**Comment by XiShanYongYe-Chang** [comment]
Maybe I can do this job.
/assign @XiShanYongYe-Chang

**Comment by RainbowMango** [comment]
Which one would you like to take?

**Comment by XiShanYongYe-Chang** [comment]
> Which one would you like to take?

EnsureWork() and retainServiceFields()

**Comment by kerthcet** [comment]
any work remained I can work with ? Newcomer to karmada.

**Comment by RainbowMango** [comment]
Hi @kerthcet Seems only one task left.
Go for it if you interest in it.

**Comment by kerthcet** [comment]
> Hi @kerthcet Seems only one task left.
> Go for it if you interest in it.

thanks.
