### ISSUE TITLE
[umbrella] [Help Wanted] [Code Writing Wanted] Add e2e Test for Lazy activation Policy

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4607]
**What would you like to be added**:

*Add e2e Test for Lazy activation Policy.*

A Lazy activation Policy is just like:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: policy-delay
spec:
  activationPreference: Lazy  # a new field added here, which refers to lazy activation Policy
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```

Then, if a policy sets this field, the policy changes will not take effect immediately but defer to the resource template changes, in other words, the resource template will not be propagated as per the current propagation rules until there is an update on resource template itself.

> You you want to known more:
> * proposal PR: #4602 
> * implemention PR: #4577
> * related issue: #4563

**Why is this needed**:

* Consolidate the test protection for the lazy activation feature.
* Help partners who are interested in the lazy activation feature to become more familiar with the detail behavior of it, and participate in contributing to the feature.
* Help beginners contributes code in karmada. 

**Which cases need to be done**:

*If you are interested in this activity, I can assign some of the e2e test to you.*

All cases are listed in [here](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#test-plan).

TODO List:

- [x] Simple Case 1 ([Policy created before resource](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#simple-case-1-policy-created-before-resource)) @Affan-7  #4622
- [x] Simple Case 2 ([Policy created after resource](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#simple-case-2-policy-created-after-resource)) @chaosi-zju #4740
- [x] Simple Case 3 ([Lazy to immediate](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#simple-case-3-lazy-to-immediate)) @hulizhe #4804
- [x] Simple Case 4 ([Immediate to lazy](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#simple-case-4-immediate-to-lazy)) @hulizhe #4804
- [ ] Combined Case 1 ([Policy deleted](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-1-policy-deleted)) @ewon78 #4668
- [ ] Combined Case 2 ([Policy no longer match](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-2-policy-no-longer-match)) @ewon78 #4668
- [x] Combined Case 3 ([Policy preemption](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-3-policy-preemption)) @Affan-7 #5033
- [x] Combined Case 4 ([Policy preemption](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-4-policy-preemption)) @hulizhe #4804
- [x] Combined Case 5 ([Propagate dependencies](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-5-propagate-dependencies)) @chaosi-zju #4740
- [x] Combined Case 6 ([Propagate dependencies](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-6-propagate-dependencies)) @chaosi-zju #4740

**Feel free to ask me if there are any problems, and feel free to ask for assignment.**

**Comment by Affan-7** [comment]
/assign

Let me give it a try.

**Comment by Affan-7** [comment]
Hi Chaosi,

I was wondering where should I add these tests. Should I add them in the `propogationpolicy_test.go`? Or should I create a new file like `lazy_activation_policy_test.go`?

**Comment by chaosi-zju** [comment]
> I was wondering where should I add these tests. Should I add them in the `propogationpolicy_test.go`? Or should I create a new file like `lazy_activation_policy_test.go`?

Hi @Affan-7, sorry for the delay, and thank you very much for your enthusiasm~

I would prefer a new file like `lazy_activation_policy_test.go`.

Besides, which cases you would like choose? I can assign cases one batch by on batch to you~ 

Because I hope that more partners can participate, which will help partners better understand this new feature. But since we are celebrating the New Year and most people are on vacation, there is not much popularity recently, haha~

**Comment by Affan-7** [comment]
I can work on  `Simple Case 1`.

> Because I actually hope that more partners can be involved, which will help partners better understand this new feature.

That sounds good! I appreciate your help and contributions to the community.

**Comment by chaosi-zju** [comment]
> I can work on `Simple Case 1`.

Okey, your great effort will provide a important example to followers~

**Comment by Affan-7** [comment]
Unassigning myself so people don't think that I am working on the whole issue.

**Comment by chaosi-zju** [comment]
> Can I work on this?

@ewon78 Hi, of course you can~

which cases would you prefer?

**Comment by zhzhuang-zju** [comment]
@chaosi-zju I can work on Simple Case 3 and Simple Case 4, thanks~

**Comment by ewon78** [comment]
@chaosi-zju thanks. I can work on Combined Case 1 & 2.

**Comment by chaosi-zju** [comment]
Ok, thank you for your enthusiasm @zhzhuang-zju @ewon78 ~

Besides, since another friend `Affan-7` has submited a PR #4622 which haven't been merged, please be careful not to have too many conflicts on file names or common codes, thanks~

**Comment by Affan-7** [comment]
Hi @chaosi-zju, can you please assign me some more test cases?

**Comment by chaosi-zju** [comment]
> can you please assign me some more test cases?

ok, of course, please just wait for a while~

**Comment by chaosi-zju** [comment]
@Affan-7 hi, Does [Combined Case 3] fit for you?

**Comment by hulizhe** [comment]
@chaosi-zju Hi, can I have a try on this?

**Comment by zhzhuang-zju** [comment]
> @chaosi-zju Hi, can I have a try on this?

I'm glad you're willing to work on this. You can take my tasks, and feel free to ask any questions~

**Comment by chaosi-zju** [comment]
@ewon78 I'm very sorry for not following up your progress for a long time. I see that your PR CI failed. Can you rebase the latest code and deal with the CI problem? If you have any questions, please feel free to contact me. Thank you very much~

**Comment by chaosi-zju** [comment]
hi @Affan-7, long time no contact, how is it going for Combined Case 3, is there any time for you to go on? ٩(๑❛ᴗ❛๑)۶

**Comment by Affan-7** [comment]
Hi @chaosi-zju, I will surely get back to it on the weekends😅. I am not getting enough time to work on it.

**Comment by chaosi-zju** [comment]
> I will surely get back to it on the weekends😅. I am not getting enough time to work on it.

OK! no rush, take your time :)
