### ISSUE TITLE
[umbrella] Cluster statue-based policy orchestration solutions

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4658]
**What would you like to be added**:

Provides a policy orchestration solution based on cluster status.

**Why is this needed**:

For specific details, please refer to #4651 

The specific work items can be planned as follows:

- [x] Add proposal for remedy feature @XiShanYongYe-Chang #4651 
- [x] Adding remedy APIs to ClusterState-based policy orchestration solutions @XiShanYongYe-Chang #4635 
- [x] Add remedy API in the swagger.json @XiShanYongYe-Chang #4675 
- [x] Example for Adding the detection component of the Service Domain Name Resolution Function for the K8S Cluster @wm775825 #4646 
- [x] Add remedy controller to reconcile with cluster status condition and remedy resource. @XiShanYongYe-Chang #4655 
- [x] Development in [multicluster-cloud-provider](https://github.com/karmada-io/multicluster-cloud-provider) repo
  - [x] Add multiclusteringress service locations controller @XiShanYongYe-Chang https://github.com/karmada-io/multicluster-cloud-provider/pull/14
  - [x] Watch Cluster.Status.RemedyActions field with multiclusteringress controller @XiShanYongYe-Chang https://github.com/karmada-io/multicluster-cloud-provider/pull/16
- [x] UT
  - [x] Add UT for remedy util function @XiShanYongYe-Chang #4686 
  - [x] Add UT for remedy controller event handler @XiShanYongYe-Chang #4686 
- [x] E2E @XiShanYongYe-Chang #5007 

Node: Task decomposition will be updated in a timely manner as the subsequent development progresses.

**Comment by XiShanYongYe-Chang** [comment]
All subtasks have been finished. Let me close it.
/close
