### ISSUE TITLE
GitHub Actions: Transitioning from Node 16 to Node 20

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#4669]
**What would you like to be added**:
Bump GitHub Actions to transition all actions to run on Node 20 as Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases).

- [x] actions/checkout@v3  --> actions/checkout@v4 (#4857)
- [x] actions/setup-go@v3  --> actions/setup-go@v5 (#4756)
- [x] arduino/setup-protoc@v1  --> arduino/setup-protoc@v3 (#4856)
- [x] codecov/codecov-action@v3  --> codecov/codecov-action@v4 (#4834)
- [x] actions/upload-artifact@v3  --> actions/upload-artifact@v4 (#4854)
- [x] engineerd/setup-kind@v0.5.0  (Seems the repo is inactive, is there a replacement?) (#4760)
- [x] azure/setup-helm@v3  --> azure/setup-helm@v4 (#4832)
- [x] actions/setup-python@v4  --> actions/setup-python@v5 (#4755)
- [ ] fossas/fossa-action@v1  --> fossas/fossa-action@v1.3.3
- [x] github/codeql-action/upload-sarif@v2  --> github/codeql-action/upload-sarif@v3 [Guide](https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/) (#4833)
- [ ] docker/login-action@v2  --> docker/login-action@v3
- [x] docker/setup-qemu-action@v2 --> docker/setup-qemu-action@v3 (https://github.com/karmada-io/karmada/pull/4754)
- [x] softprops/action-gh-release@v1 --> softprops/action-gh-release@v2 (#4757)
- [x] helm/kind-action@v1.7.0 --> helm/kind-action@v1.9.0 (#4753)

**Why is this needed**:
See the [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

**Comment by karnatisrinivas** [comment]
Hello @RainbowMango , Can you assign this issue to me, I would like to work on it.

**Comment by RainbowMango** [comment]
Sure, go for it. Thanks.
/assign @karnatisrinivas

**Comment by RainbowMango** [comment]
> engineerd/setup-kind@v0.5.0 (Seems the repo is inactive, is there a replacement?)

Just looked at the [helm/kind-action](https://github.com/helm/kind-action) which looks like a good candidate for the `engineerd/setup-kind`.

In addition, I run a simple test and it works fine:
- code change: https://github.com/karmada-io/karmada/commit/bde3cc85a7825855e776c30d64bae3e4835fde8b
- workflow logs: https://github.com/RainbowMango/karmada/actions/runs/8135021485

**Comment by RainbowMango** [comment]
kindly ping @karnatisrinivas, are you still working on this? Feel free to let me know if you need any help.

**Comment by liangyuanpeng** [comment]
@karnatisrinivas  Hi, I have create a PR #4714 to auto update github-actions, And you still can work for `engineerd/setup-kind@v0.5.0 (Seems the repo is inactive, is there a replacement?)
`

**Comment by RainbowMango** [comment]
/unassign @karnatisrinivas 
As no response from @karnatisrinivas .

**Comment by RainbowMango** [comment]
/assign @RainbowMango @liangyuanpeng 
I will take the `engineerd/setup-kind` and perhaps the dependant bot could help with the others.

**Comment by RainbowMango** [comment]
I'm going to close this issue as the dependabot will fix them sooner or later. 
Note: Now dependabot will upgrade at most 5 dependencies a week.
