### ISSUE TITLE
[Umbrella] Align generation and observedGeneration fields by reflectstatus and aggregatestatus operation

### ISSUE THREAD

**Issue by yike21** [karmada-io/karmada#4870]
**What would you like to be added**:
There are some third-party resources and native resources that need to align `.metadata.generation`  and `.status.observedGeneration ` fields. Please ref to #4866 .

**Why is this needed**:

Continue the work of #4867  and break down the tasks to be done.
- Native resource
  - [x] GroupVersion: apps/v1
    Kind: 
      - [x] Deployment @veophi #4867 
      - [x] DaemonSet @whitewindmills #5165 
      - [x] StatefulSet @liangyuanpeng #5204
- Thirdparty resource
  - [x] GroupVersion: apps.kruise.io/v1alpha1
    Kind: 
      - [x] CloneSet @veophi #5057
      - [x] DaemonSet @whitewindmills #5167 
  - [x] GroupVersion: apps.kruise.io/v1beta1
    Kind: 
      - [x] StatefulSet @zhy76 #5094
  - [x] GroupVersion: helm.toolkit.fluxcd.io/v2beta1
    Kind: 
      - [x] HelmRelease @yike21 #5311 
  - [x] GroupVersion: kustomize.toolkit.fluxcd.io/v1
    Kind: 
      - [x] Kustomization @yike21 #5084 
  - [x] GroupVersion: source.toolkit.fluxcd.io/v1
    Kind: 
      - [x] GitRepository @yike21 #5086 
  - [x] GroupVersion: source.toolkit.fluxcd.io/v1beta2
    Kind: 
     - [x] Bucket @yike21  #5193 
     - [x] HelmChart @yike21 #5194
     - [x] HelmRepository @yike21 #5196
     - [x] OCIRepository @yike21 #5197

We need to examine the meaning of `.metadata.generation` and `.status.observedGeneration` fields for each resource above, and then modify the `ReflectStatus` and `AggregateStatus` operations to align them. The modifications are likely to be similar, so please wait for `CloneSet` and `Deployment` modifications to be completed.

/help

**Comment by liangyuanpeng** [comment]
I want to try it for StatefulSet

**Comment by yike21** [comment]
> I want to try it for StatefulSet

Thanks a lot~

**Comment by XiShanYongYe-Chang** [comment]
@yike21 Good Job!

**Comment by whitewindmills** [comment]
I wanna pick up `DaemonSet`, thanks.

**Comment by yike21** [comment]
> I wanna pick up `DaemonSet`, thanks.

ok, thanks a lot~

**Comment by zhy76** [comment]
I am also concerned about this question. What is the current progress of cloneset? I can get involved in this issue about other resource, too

**Comment by XiShanYongYe-Chang** [comment]
It will continue to advance in the next version.

**Comment by XiShanYongYe-Chang** [comment]
Hello everyone, we can continue this issue.
@veophi @yike21 @whitewindmills @liangyuanpeng

**Comment by Akash-Singh04** [comment]
Hey is this issue still open? if so, I would like to work on it

**Comment by yike21** [comment]
> Hey is this issue still open? if so, I would like to work on it

Thanks! you can choose what you are interested in.

**Comment by zhy76** [comment]
Can I work on apps.kruise.io/v1beta1 statefulset?

**Comment by yike21** [comment]
> Can I work on apps.kruise.io/v1beta1 statefulset?

ok, thanks a lot~

**Comment by Akash-Singh04** [comment]
Can we get started on this issue or should we wait for #5057 to be completed? I would like to work on helm.toolkit.fluxcd.io/v2beta1

**Comment by yike21** [comment]
> Can we get started on this issue or should we wait for #5057 to be completed? I would like to work on helm.toolkit.fluxcd.io/v2beta1

Thanks, let's start this issue! We need to modify `AggregateStatus` and `statusReflection`, then update testdata to characterize the new customizations.

**Comment by liangyuanpeng** [comment]
> Hello everyone, we can continue this issue.
> @veophi @yike21 @whitewindmills @liangyuanpeng

I will open a PR for StatefulSet in this week.

**Comment by RainbowMango** [comment]
/reopen
as closed by #5196 by mistake.

**Comment by XiShanYongYe-Chang** [comment]
Kind ping @Akash-Singh04, do you have time to make a PR?

**Comment by XiShanYongYe-Chang** [comment]
Hi @yike21, we have one sub-mission left.

**Comment by yike21** [comment]
> Hi @yike21, we have one sub-mission left.

Hi @XiShanYongYe-Chang ! Let's wait a little bit for @Akash-Singh04 . If Akash-Singh04 is busy, I'll finish this part as soon as possible during the week.

**Comment by Akash-Singh04** [comment]
Hey @XiShanYongYe-Chang Currently busy, feel free to make a PR :)

**Comment by RainbowMango** [comment]
It seems all tasks are done.  Great job! @yike21 
Thanks to everyone who contribute to this task.
/close

**Comment by yike21** [comment]
Thank you all for the contributions!
