### ISSUE TITLE
OSPP 2024 Project tracking

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4879]
All of Karmada projects have been released:

https://summer-ospp.ac.cn/org/projectlist?lang=zh&pageNum=1&pageSize=50&programName=Karmada

This issue will track the progress of all projects, and students are welcome to sign up for it.

- [x] [Minimizing the RBAC Permission of the Karmada Component](https://summer-ospp.ac.cn/org/prodetail/245c40153?lang=zh&list=pro) 
  - mentor @zhzhuang-zju 
  - track issue #5182 
  - selected students @B1F030
- [x] [The karmadactl supports installation and deployment of the production-level environment using configuration files.](https://summer-ospp.ac.cn/org/prodetail/245c40186?lang=zh&list=pro) 
  - mentor @liangyuanpeng 
  - tracking issue #5387
  - proposal #5277 
  - selected students @tiansuo114 
- [x] [Karmada evenly allocates the replicas based on the spread constraint.](https://summer-ospp.ac.cn/org/prodetail/245c40281?lang=zh&list=pro) 
  - mentor @whitewindmills 
  - track issue #5159 
  - selected students @ipsum-0320
- [x] [Karmada supports the dynamic configuration mechanism of OverridePolicy.](https://summer-ospp.ac.cn/org/prodetail/245c40337?lang=zh&list=pro) 
  - mentor @chaunceyjiang 
  - track issue #5608
  - proposal #5449 
  - selected students @sophiefeifeifeiya 
- [x] [Karmada Dashboard Automation i18n Tool](https://summer-ospp.ac.cn/org/prodetail/245c40338?lang=zh&list=pro) 
  - mentor @warjiang 
  - proposal https://github.com/karmada-io/dashboard/pull/119
  - selected students @chouchongYHMing 
- [x] [The Override Policy management function of the Karmada Dashboard is implemented.](https://summer-ospp.ac.cn/org/prodetail/245c40342?lang=zh&list=pro) 
  - mentor @samzong
- [x] [Karmadactl Function Supplementation and Operation Experience Improvement](https://summer-ospp.ac.cn/org/prodetail/245c40397?lang=zh&list=pro) 
  - mentor @RainbowMango 
  - track issue #5248 
  - selected students @hulizhe
- [x] [Karmada supports smooth rollback of a single cluster.](https://summer-ospp.ac.cn/org/prodetail/245c40436?lang=zh&list=pro) 
  - mentor @chaosi-zju 
  - track issue #5380 
  - selected students @wulemao

**Comment by whitewindmills** [comment]
task tracking: https://github.com/karmada-io/karmada/issues/5159

**Comment by XiShanYongYe-Chang** [comment]
All projects have been finished, thanks to all of you! 👍 
/close
