### ISSUE TITLE
Bump Kubernetes related dependencies

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#4907]
**What would you like to be added**:
Bump Kubernetes related dependencies:
- [x] Bump Kubernetes dependencies to v1.29.4. (@RainbowMango, #4884)
- [x] Bump sigs.k8s.io/metrics-server to v0.7.1(which also rely Kubernetes v1.29). (@RainbowMango, #4904)
- [x] Bump sigs.k8s.io/controller-runtime to v0.17.5(which also rely Kubernetes v1.29). (@seanlaii, [#4921](https://github.com/karmada-io/karmada/pull/4921))
- [x] Bump sigs.k8s.io/kind to [v0.22.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.22.0). (@whitewindmills, #4909)
- [x] Bump sigs.k8s.io/cluster-api to [v1.7.1](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.1). (@zhzhuang-zju, [#4923](https://github.com/karmada-io/karmada/pull/4923))
- [x] Bump Golang version to v1.21.10(planed on Tuesday, May 7). (@zhzhuang-zju, #4920)
- [ ] Bump [golangci-lint](https://github.com/karmada-io/karmada/blob/98c6158c06f51998ddce2f01ef7b10a5fd082754/hack/verify-staticcheck.sh#L22) to [v1.58.0](https://github.com/golangci/golangci-lint/releases/tag/v1.58.0).

**Why is this needed**:

**Comment by whitewindmills** [comment]
pick this one `Bump sigs.k8s.io/kind to v0.22.0`, thanks.

**Comment by RainbowMango** [comment]
ok, updated.

**Comment by RainbowMango** [comment]
Note:
Go 1.21.10 was relased.
https://go.dev/doc/devel/release#go1.21.10

**Comment by RainbowMango** [comment]
@zhzhuang-zju Would you like to help with this?

**Comment by zhzhuang-zju** [comment]
> @zhzhuang-zju Would you like to help with this?

yes, very willing to

/assign

**Comment by seanlaii** [comment]
Hi, is anyone working on the controller-runtime upgrade? If not, I can help with it.

**Comment by zhzhuang-zju** [comment]
> Hi, is anyone working on the controller-runtime upgrade? If not, I can help with it.

Hi @seanlaii Judging from the progress of the task, no one is currently working on it yet. 

Ask @RainbowMango and @whitewindmills to confirm

**Comment by RainbowMango** [comment]
@seanlaii just go for it. Thanks. i will assign it to you. Thanks.
Just a notice, there is a breaking change you might need to handle, not a hard one, as well as a unit test that might need to fix.

**Comment by zhzhuang-zju** [comment]
@RainbowMango pick this one `Bump sigs.k8s.io/cluster-api to v1.7.1`, thanks.

**Comment by RainbowMango** [comment]
Done. Assigned it to you.
