### ISSUE TITLE
[Umbrella] Enhancement of Karmada maturity based on Clomonitor check sets

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#5048]
**What would you like to be added**:
[CLOMonitor](https://clomonitor.io/) is a tool that periodically checks open source projects repositories to verify they meet certain project health best practices, and will provide a score card for each project based on the check results. Here is the score card for karmada: https://clomonitor.io/projects/cncf/karmada. As you can see, there's still some work to be done.
Here list the check set that karmada did not pass.
- [x] [license scanning](https://clomonitor.io/docs/topics/checks/#license-scanning) (@B1F030 #5050)
   Karamda completes the license scanning software scans in [fossa](https://github.com/karmada-io/karmada/blob/master/.github/workflows/fossa.yml) workflow, so we only need add the `FOSSA` link in the `README` file. Regexps used: `"(https://app.fossa.(?:io|com)/projects/[^"'\)]+)"`

- [x] [Artifact Hub badge](https://clomonitor.io/docs/topics/checks/#artifact-hub-badge) (@B1F030 #5051)

- [x] [OpenSSF Scorecard badge](https://clomonitor.io/docs/topics/checks/#openssf-scorecard-badge) (@B1F030 #5055)
We have added the `OpenSSF` Scorecard badge in the `README` file in #5022, but the url `https://api.scorecard.dev/projects/github.com/karmada-io/karmada/badge` does not match the specified regexps `"(https://api.securityscorecards.dev/projects/github.com/[^/]+/[^/]+)/badge"` and needs to be modified.

- [x] [Dependencies policy](https://clomonitor.io/docs/topics/checks/#dependencies-policy) （@zhzhuang-zju）

- [x] [Software bill of materials (SBOM)](https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom)(@zhzhuang-zju #5110)

- [x] [Security insights](https://clomonitor.io/docs/topics/checks/#security-insights) (@zhzhuang-zju, #5140)

- [x] [Signed releases](https://clomonitor.io/docs/topics/checks/#signed-releases-from-openssf-scorecard)
Karmada images have been signed with `cosign` since `release1.7`, but we need add the [SLSA provenance file](https://slsa.dev/spec/v0.1/index) in the assets for release (*.intoto.jsonl) (@zhzhuang-zju #5178)

- [x] [Token permissions](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard)
define topLevel permission for each workflow
   - [x] [ci-image-scanning.yaml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-image-scanning.yaml) (@aditya7302 #5059)
   - [x] [ci-schedule-compatibility.yaml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-schedule-compatibility.yaml) (@aditya7302 #5068 )
   - [x] [ci-schedule.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-schedule.yml) (@aditya7302  #5069)
   - [x] [ci.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci.yml) (@Akash-Singh04 #5078)
   - [x] [cli.yaml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/cli.yaml) (@Akash-Singh04 #5079)
   - [x] [dockerhub-latest-chart.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/dockerhub-latest-chart.yml) (@aditya7302 #5082)
   - [x] [dockerhub-latest-image.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/dockerhub-latest-image.yml) (@zhzhuang-zju #5123)
   - [x] [dockerhub-released-chart.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/dockerhub-released-chart.yml) (@zhzhuang-zju #5123)
   - [x] [dockerhub-released-image.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/dockerhub-released-image.yml) (@zhzhuang-zju #5123)
   - [x] [fossa.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/fossa.yml) (@aditya7302 #5080)
   - [x] [lint-chart.yaml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/lint-chart.yaml)(@aditya7302 #5081 )
   - [x] [release.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/release.yml) (@zhzhuang-zju #5123)
   - [x] [swr-latest-image.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/swr-latest-image.yml) (@zhzhuang-zju #5123)
   - [x] [swr-released-image.yml](https://github.com/karmada-io/karmada/blob/master/.github/workflows/swr-released-image.yml) (@zhzhuang-zju #5123 )
- [x] [Roadmap](https://clomonitor.io/docs/topics/checks/#roadmap) (@zhzhuang-zju https://github.com/karmada-io/community/pull/78)
- [x] [Summary Table](https://clomonitor.io/docs/topics/checks/#summary-table) (@RainbowMango https://github.com/cncf/landscape/pull/3976)

**Reference**: 
- https://clomonitor.io/projects/cncf/karmada
- https://clomonitor.io/docs/topics/checks/
- https://scorecard.dev/viewer/?uri=github.com/karmada-io/karmada

**Why is this needed**:
Improving scores is not the ultimate goal, I hope to use this issue to make Karmada healthier and more mature

**Comment by zhzhuang-zju** [comment]
cc @B1F030

**Comment by B1F030** [comment]
I'm glad to help! Can I take the `license scanning` first?

**Comment by RainbowMango** [comment]
Maybe we can have  the badge of CLomonitor. See example at https://github.com/kubeflow/kubeflow/blob/master/README.md.
[![CLOMonitor](https://img.shields.io/endpoint?url=https://clomonitor.io/api/projects/cncf/karmada/badge)](https://clomonitor.io/projects/cncf/karmada)

**Comment by aditya7302** [comment]
@RainbowMango I have added the CLOMonitor badge in my PR.

**Comment by Akash-Singh04** [comment]
Hey does this issue require any more help?If so,  I would like to work on it

**Comment by zhzhuang-zju** [comment]
> Hey does this issue require any more help?If so, I would like to work on it

Sure, go ahead. Please pick what interests you and do it~

**Comment by aditya7302** [comment]
@RainbowMango @zhzhuang-zju I have added top-level permission for ci-image-scanning workflow. Please review it.

**Comment by Akash-Singh04** [comment]
@RainbowMango @zhzhuang-zju I have added top-level permission for ci.yml and cli.yml workflow. Please review it.

**Comment by zhzhuang-zju** [comment]
@aditya7302 @Akash-Singh04 Thanks for your efforts on task [Token permissions](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard). Defining the minimal permission set for workflow is actually difficult, do you have any experiences to share? Besides, how can we effectively go about verifying the results(all I can think of at the moment is local verification)? Other than that, have you encountered any other difficulties? Looking forward to your feedback!

**Comment by zhzhuang-zju** [comment]
> @aditya7302 @Akash-Singh04 Thanks for your efforts on task [Token permissions](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard). Defining the minimal permission set for workflow is actually difficult, do you have any experiences to share? Besides, how can we effectively go about verifying the results(all I can think of at the moment is local verification)? Other than that, have you encountered any other difficulties? Looking forward to your feedback!

I found the recommended steps and an online tool to complete the task [Token permissions](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard)!
refer to https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions:
> The highest score is awarded when the permissions definitions in each workflow's yaml file are set as read-only at the [top level](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions) and the required write permissions are declared at the [run-level](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idpermissions).

Following this criterion, the recommended steps are:
- Set top-level permissions as read-all or contents: read as described in GitHub's [documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions).
- Set any required write permissions at the job-level. Only set the permissions required for that job; do not set permissions: write-all at the job level.

So, we had a problem with the previous implementation and needed to be revised.

To help determine the permissions needed for our workflows, we can use [StepSecurity's online tool](https://app.stepsecurity.io/secureworkflow/) by ticking the "Restrict permissions for GITHUB_TOKEN". 
NOTE: Cleanup workflow's previously defined permissions before using it, and the result may be more precise.

**Comment by zhzhuang-zju** [comment]
> @zhzhuang-zju As I am new to learning workflows, I primarily use local verification to test them. This method helps me ensure that the workflows function correctly within a controlled environment. However, I think that defining the minimal permission set for large workflows can be quite challenging.

I can't agree more~  Local verification  is actually the safest way.  Now with the tool Scan, this process is even easier. However, in some cases, the tool's database does not have permissions information of a certain action, we can only verify them locally or refer to other user-defined permissions.
BTW, thank @aditya7302 and @Akash-Singh04  for your contributions.

**Comment by RainbowMango** [comment]
All tasks are done! Thank you all for your hard work! @B1F030 @zhzhuang-zju @aditya7302 @SkySingh04 

For now, we reached a 99 score, and the last check(`Signed releases`) will pass after 5 releases, there is nothing we need to do on our part.

/close
