### ISSUE TITLE
Define metrices port name in container field of related karmada components

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#5166]
**What would you like to be added**:

Define metrices port name in container field of related karmada components, so that the port name can be specified in [PodMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#using-podmonitors) to form prothumes metrics dashboard.

**Why is this needed**:

Detail info refers to #4877

**TODO list:**

* Helm installation:

- [x] Expose the default port  for the karmada-controller-manager, scheduler and agent when creating a PodMonitor. #5139
- [x] Expose the metrics port  for the karmada-webhook、karmada-operator、descheduler and scheduler-estimator in helm #5168

* karmadactl installation:
- [x] Expose the metrics port  for the karmada-controller-manager, scheduler、agent、karmada-webhook、descheduler and scheduler-estimator in karmadactl init #5169

* karmada-operator installation:
- [x] Expose the metrics port  for the karmada-controller-manager, scheduler、karmada-webhook、descheduler in karmada-operator #5465

* local-up installation:
- [x] Expose the metrics port  for the karmada-controller-manager, scheduler、agent、karmada-webhook、descheduler and scheduler-estimator in local-up-karmada. #5428

**Comment by whitewindmills** [comment]
[Helm]
> Expose the metrics port for the karmada-webhook、karmada-operator、descheduler and scheduler-estimator in helm

[karmadactl]
>  Expose the metrics port for the karmada-controller-manager, scheduler、agent、karmada-webhook、karmada-operator、descheduler and scheduler-estimator in karmadactl init

/assign

**Comment by RainbowMango** [comment]
/close
As all tasks are done. Thank you guys who contributed to this effort. @chaosi-zju @dzcvxe @whitewindmills @wangxf1987
