### ISSUE TITLE
[Umbrella] Support for cluster-level resource propagation pause and resume capabilities

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#5217]
**What would you like to be added:**

Support for cluster-level resource propagation pause and resume capabilities.

**Why is this needed:**

Received feedback from multiple issues, and there is a hope that Karmada can provide the capability to pause distribution, allowing users to expand more capabilities with it.

Related issue: https://github.com/karmada-io/karmada/issues/1567, https://github.com/karmada-io/karmada/issues/4421, https://github.com/karmada-io/karmada/issues/4688, https://github.com/karmada-io/karmada/issues/4559

- [x] Add proposal for this feature @XiShanYongYe-Chang #5118
- [x] API Modification @a7i #4838 
  - [x] PropagationPolicy/ClusterPropagationPolicy
  - [x] ResourceBinding/ClusterResourceBinding
  - [x] Work
- [x] Implement the capability to pause resource distribution in the controller.
  - [x] Suspension field transfer and distribution judge @a7i #4838
  - [x] Handle with suspension status condition @a7i #5317
  - [x] Webhook validate @a7i #5282 
  - [x] Add event to describe work dispatching condition @a7i #5332 
- [x] Test for the feature
  - [x] UT
  - [x] E2E @a7i #4838 #5317 #5354
- [x] Add user documentation for this feature. @a7i https://github.com/karmada-io/website/pull/668

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i, I created a umbrella issue for resource propagation pause.
/cc @a7i

**Comment by a7i** [comment]
Awesome! I will start on https://github.com/karmada-io/karmada/pull/4838 tomorrow to align with the new proposal.

**Comment by XiShanYongYe-Chang** [comment]
Thanks a lot @a7i we've completed all the subtasks.
Looking forward to the feedback from different partners in the community. Let's keep iterating this feature.
/close
