### ISSUE TITLE
[Umbrella] Specification of merics and health probe port parameters

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#5219]
**What would you like to be added**:

Currently, the port parameter definitions of the metrics and health probes are different for each component, which will cause some ambiguity to users, so we plan to standardize the port definitions of each component.

- karmada-operator:
  * `--secure-port` & `--bind-address`: only for http health probe
  * `--metrics-bind-address`: only for metrics
- karmada-agent:
  * `--secure-port` & `--bind-address`: only for http health probe
  * `--metrics-bind-address`: only for metrics
- karmada-controller-manager:
  * `--secure-port` & `--bind-address`: only for http health probe
  * `--metrics-bind-address`: only for metrics
- karmada-descheduler:
  * `--secure-port` & `--bind-address`: for http health probe and metrics
- karmada-scheduler:
  * `--secure-port` & `--bind-address`: for http health probe and metrics
- karmada-scheduler-estimator:
  * `--secure-port` & `--bind-address`: for http health probe and metrics
  * `--server-port`: grpc server port
- karmada-webhook:
  * `--secure-port` & `--bind-address`: only for webhook server
  * `--metrics-bind-address`: only for metrics
  * `--health-probe-bind-address`: only for http health probe
 
This will be basically the same as controller-manager:
```go
// MetricsBindAddress is the TCP address that the controller should bind to
// for serving prometheus metrics.
// It can be set to "0" to disable the metrics serving.
MetricsBindAddress string

// HealthProbeBindAddress is the TCP address that the controller should bind to
// for serving health probes
// It can be set to "0" to disable serving the health probe.
HealthProbeBindAddress string
```

**Note that you need to mark the old parameters as deprecated and we will remove them in a later version.**

- [x] karmada-operator: https://github.com/karmada-io/karmada/pull/5174
- [x] karmada-agent: https://github.com/karmada-io/karmada/pull/5223
- [x] karmada-controller-manager: https://github.com/karmada-io/karmada/pull/5290
- [x] karmada-descheduler: https://github.com/karmada-io/karmada/pull/5435
- [x] karmada-scheduler: @liangyuanpeng https://github.com/karmada-io/karmada/pull/5437
- [x] karmada-scheduler-estimator: https://github.com/karmada-io/karmada/pull/5273

**Comment by RainbowMango** [comment]
Great thanks to @whitewindmills for picking this. 
We may need two releases to finish this, this release focuses on introducing the new one and depreciating the outdated one. And remove the deprecated flags in the next release.  Are we on the same page?

**Comment by liangyuanpeng** [comment]
/assign 
for karmada-scheduler

**Comment by whitewindmills** [comment]
> Are we on the same page?

SURE

**Comment by liangyuanpeng** [comment]
@whitewindmills 
I checked the webhook and saw that it was working as expected so there was no need to do anything, am I understanding this correctly?

**Comment by whitewindmills** [comment]
@liangyuanpeng yes, but it's comments need to be fixed.
```go
// HealthProbeBindAddress is the TCP address that the controller should bind to
// for serving health probes
// It can be set to "0" or "" to disable serving the health probe.
```

**Comment by seanlaii** [comment]
Hi, I am glad to help! Can I take karmada-scheduler-estimator?

**Comment by seanlaii** [comment]
/assign
for karmada-scheduler-estimator

**Comment by whitewindmills** [comment]
@seanlaii thanks

**Comment by seanlaii** [comment]
Hi, I can also take karmada-controller-manager.

**Comment by whitewindmills** [comment]
@seanlaii go for it

**Comment by whitewindmills** [comment]
I think we should complete those tasks before the next release.
@liangyuanpeng are you free to do it?

**Comment by whitewindmills** [comment]
ping @liangyuanpeng 
if you are not available, please let me know. I'll help you with this.

**Comment by liangyuanpeng** [comment]
sorry for my late, let me open a PR in this week

**Comment by RainbowMango** [comment]
Let's try to finish this by this week, that means all components share the same deprecation cycle.

**Comment by RainbowMango** [comment]
@whitewindmills We have [11 componets](https://github.com/karmada-io/karmada/blob/3ccbf136824dc1ec6b43d7d5c8f7ae9d2e06288d/Makefile#L11-L21) now, I see you just listed 6 components, have you checked the others?

**Comment by whitewindmills** [comment]
> have you checked the others?

yes

* **karmada-webhook**: working as expected, do nothing.
* **karmada-interpreter-webhook-example, karmada-search, karmada-metrics-adapter, karmada-aggregated-apiserver**: they have no such merics and health probe parameters.

**Comment by RainbowMango** [comment]
OK. Thanks for the clarification.

**Comment by RainbowMango** [comment]
For the `karmada-interpreter-webhook-example`:
```
Generic flags:
      --bind-address string                                                                                                                                                                                                  
                The IP address on which to listen for the --secure-port port. (default "0.0.0.0")
      --secure-port int                                                                                                                                                                                                      
                The secure port on which to serve HTTPS. (default 8445)
```
Shall we change it to `--health-probe-bind-address`?

**Comment by RainbowMango** [comment]
Same for `karmada-search`:
```
      --bind-address ip                                                                                                                                                                                                      
                The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank or an unspecified address (0.0.0.0 or
                ::), all interfaces and IP address families will be used. (default 0.0.0.0)
      --secure-port int                                                                                                                                                                                                      
                The port on which to serve HTTPS with authentication and authorization. If 0, don't serve HTTPS at all. (default 443)
```

**Comment by whitewindmills** [comment]
> Shall we change it to --health-probe-bind-address?

but they're used to listen for the webhook server, not healthz.

**Comment by RainbowMango** [comment]
Get it.
