### ISSUE TITLE
Enhance karmadactl operation and maintenance experience

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#5249]
**What would you like to be added**:
Refer to https://github.com/karmada-io/karmada/issues/4291 and https://github.com/karmada-io/karmada/issues/5248, we have decided to continuously improve and enhance the user experience of karmadactl in upcoming releases. To track the progress of the project, we will divide it into the following subtasks:
- [x] proposal: Analyzing and designing the flag sets and behavior of the commands. (@hulizhe #5245)

Implement new Commands
- [x] karmadactl create (@hulizhe #5399 )
- [x] karmadactl patch (@zhzhuang-zju #5463)
- [x] karmadactl delete (@zhzhuang-zju #5431)
- [x] karmadactl label (@zhzhuang-zju #5453)
- [x] karmadactl annotate (@zhzhuang-zju #5458)
- [x] karmadactl edit (@zhzhuang-zju #5434) 
- [x] karmadactl attach  (@hulizhe #5395)
- [x] karmadactl api-resources (@hulizhe #5394)
- [x] karmadactl explain  (@hulizhe #5393)

Modification of Existing Commands:
- [x] karmadactl get (@hulizhe #5254)
- [x] karmadactl describe (@hulizhe #5392)
- [x] karmadactl top pod (@hulizhe #5452)
- [x] karmadactl exec(@hulizhe #5398)
- [x] karamdactl top node (@zhzhuang-zju #4224)

Note: 
- The flag sets and command behavior need to be consistent with [Proposal #5245](https://tongyi.aliyun.com/qianwen/?spm=5176.28326591.0.0.40f76ee1zBYunq&sessionId=b7b05f8e5ba3469cbfe939bb1f61378a#5245).
- If there are any other requirements or concerns regarding karmadactl, please feel free to discuss them.
- The subtasks may undergo changes.

**Comment by zhzhuang-zju** [comment]
cc @IonBoleac

**Comment by Affan-7** [comment]
Hi @zhzhuang-zju Can I get a task that is easier in this issue?

**Comment by zhzhuang-zju** [comment]
> Hi @zhzhuang-zju Can I get a task that is easier in this issue?

@Affan-7 Sure~you can take `karmadactl patch` first, Because this command only works on the Karmada control plane and does not involve switching member clusters, it is relatively easy to get started with

> Is there an explanation of every command that what they must do?

you can refer to https://github.com/karmada-io/karmada/pull/5245, it contains the flag sets and behavior of the commands.

**Comment by liangyuanpeng** [comment]
all of PRs for the new command need the release-note ^^^
cc @hulizhe

**Comment by hulizhe** [comment]
> all of PRs for the new command need the release-note ^^^ cc @hulizhe

thanks for the reminder

**Comment by zhzhuang-zju** [comment]
@IonBoleac @Affan-7 I hope to include the enhancements to karmadactl in the release 1.11.0, so I have completed the remaining work for this issue. However, this is just the first phase of enhancing karmadactl capabilities, and there will be further work to follow. I welcome your continued participation in the subsequent efforts, thanks~

**Comment by RainbowMango** [comment]
All tasks planed in this round are done. 
/close
