### ISSUE TITLE
[Release-1.12] Enhance karmadactl operation and maintenance experience

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#5477]
**What would you like to be added**:
We have completed the functionality alignment for the `karmadactl` command in release-1.11, for details, please refer to #5249.

The optimization of `karmadactl` is an ongoing effort, and recently, quite a few contributors have been involved in enhancing the capabilities of the karmadactl command. :wave::wave:
To track the progress of optimizations related to `karmadactl` more efficiently, this issue will be used to collect the PRs for current karmadactl capability enhancements. Future optimizations for `karmadactl` will also be announced through this issue.

- [ ] karmadactl init supports deployment through configuration files（@tiansuo114 #5357）
- [ ] karmadactl support rebalance command to trigger a fresh rescheduling (@chaosi-zju #5471)
- [ ] add new command `port-forward` to forward one or more local ports to a pod (@zhzhuang-zju #5464)
- [ ] enable karmada-data flag in karmadactl register cmd (@mohamedawnallah #5429)
- [ ] karmada init: support multiple label selection ability with flag EtcdNodeSelectorLabels. (@tiansuo114 #5321)
- [ ] add new command `karmadactl config image list` to list all required images from the specified private image registry (@tiansuo114 #5306)

**Comment by tiansuo114** [comment]
Hello, I would like to ask if you have already started working on the two topics: karmadactl completion: support output shell completion code for `fish` shell or karmadactl completion: support output shell completion code for `powershell` shell? If possible, I would like to try contributing code for these topics. :)

**Comment by zhzhuang-zju** [comment]
> @tiansuo114 very welcome, you can pick up any one of them, and I'll assign the task to you

assigned

**Comment by zhzhuang-zju** [comment]
All tasks have been completed or closed, so let's close this issue for now. If there are new requirements for Karmada optimization in the future, we can revisit the discussion.
