### ISSUE TITLE
[Umbrella] Update the karmada repository documentation

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#5484]
**Task description**:
Karmada released the latest version `release-1.11` on August 31, 2024. With the release of the new version, some of the documentation in the Karmada repository is now outdated and needs to be updated.

- [x] update [ci-schedule-compatibility.yaml] (https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-schedule-compatibility.yaml) (@liangyuanpeng #5514)

We have stopped updating images for release-1.8 and added  release-1.11 in #5504, and the `karmada-version` in [ci-schedule-compatibility.yaml] (https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-schedule-compatibility.yaml) should be updated

- [x] update [sample file of karmada operator](https://github.com/karmada-io/karmada/blob/master/operator/config/samples/karmada.yaml) (@MAVRICK-1 #5707 )

The [sample file](https://github.com/karmada-io/karmada/blob/master/operator/config/samples/karmada.yaml) specifies the image tags for various Karmada components, as well as for etcd and kube-apiserver. While dynamic configuration is desired, manual updates are still necessary until a solution is implemented. Currently, the image tags for Karmada components in the sample file are `v1.8.0` and need to be upgraded to `v1.11.1`.

- [x] update [CHANGELOGS.md](https://github.com/karmada-io/karmada/blob/master/CHANGELOG.md) (@MAVRICK-1 #5708)

Currently, the [CHANGELOGS.md](https://github.com/karmada-io/karmada/blob/master/CHANGELOG.md) file displays links to the changelogs for various versions. It is incomplete and also difficult to maintain. Just add a link to https://github.com/karmada-io/karmada/tree/master/docs/CHANGELOG would be ok. just like
```md
# CHANGELOGs

[CHANGELOG](./docs/CHANGELOG/)
```

- [x] update [hack/scan-image-vuln.sh](https://github.com/karmada-io/karmada/blob/master/hack/scan-image-vuln.sh) (@MAVRICK-1 https://github.com/karmada-io/karmada/pull/5710 )

Trivy is used in both [ci image-scanning](https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-image-scanning.yaml) and [hack/scan-image-vuln.sh](https://github.com/karmada-io/karmada/blob/master/hack/scan-image-vuln.sh). The version of Trivy used in the CI action is `v0.56.1`. To provide a consistent experience for image-scanning both locally and in the GitHub CI, the version of Trivy used in scan-image-vuln.sh is being upgraded from `v0.48.1` to `v0.56.1`.

- [x] update [charts/index.yaml](https://github.com/karmada-io/karmada/blob/master/charts/index.yaml) (@chaosi-zju #5579)

The file  [charts/index.yaml](https://github.com/karmada-io/karmada/blob/master/charts/index.yaml) records the version information for the karmada chart. Currently, the latest chart version recorded in charts/index.yaml is `karmada-chart-v1.9.0.tgz`. It is necessary to add `karmada-chart-v1.10.0.tgz` and update the latest version to `karmada-chart-v1.11.0.tgz`.

Ways to obtain key information:
created: refer to https://github.com/karmada-io/karmada/pull/4051#discussion_r1324310397
digest： https://github.com/karmada-io/karmada/releases/download/v1.11.0/karmada-chart-v1.xxx.xxx.tgz.sha256
```md
d4d9bbbda5ac03a4ba9349b17973b3df9047849398735dcb36cec4ec39140046 # the digest of the chart
hack/../_output/charts/karmada-chart-v1.11.0.tgz
```

PRs for reference： https://github.com/karmada-io/karmada/pull/4671

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by zhzhuang-zju** [comment]
@a7i Could you please guide me on how to get the created time in [charts/index.yaml](https://github.com/karmada-io/karmada/blob/master/charts/index.yaml)? thanks~

https://github.com/karmada-io/karmada/blob/e579560af57f9d370295b94b3a33b102f464413a/charts/index.yaml#L6

**Comment by zhzhuang-zju** [comment]
> are you working on task `update charts/index.yaml`?
> 
> if you haven't start it, you can assign it to me

sure, very welcome~
And if it’s convenient for you, could you please guide me on how to obtain the created time? This would provide helpful instructions for future contributors.

**Comment by zhzhuang-zju** [comment]
> I remember we could refer to this: [#4051 (comment)](https://github.com/karmada-io/karmada/pull/4051#discussion_r1324310397)

thanks~ I'll update it in the task description

**Comment by zhzhuang-zju** [comment]
> Just add a link to https://github.com/karmada-io/karmada/tree/master/docs/CHANGELOG would be ok.

good idea~ I have update it in the task description

**Comment by liangyuanpeng** [comment]
https://github.com/karmada-io/karmada/tree/master?tab=readme-ov-file#kubernetes-compatibility
need to update

**Comment by zhzhuang-zju** [comment]
> https://github.com/karmada-io/karmada/tree/master?tab=readme-ov-file#kubernetes-compatibility need to update

Yeah, you're right. However, updating file [kubernetes-compatibility](https://github.com/karmada-io/karmada/tree/master?tab=readme-ov-file#kubernetes-compatibility) is relatively difficult and might not be appropriate for a `good first issue`.

**Comment by Nishant-k-sagar** [comment]
I would like to work on this issue
/assign

**Comment by zhzhuang-zju** [comment]
> I would like to work on this issue

@Nishant-k-sagar welcome~, which task are you interested in?

**Comment by zhzhuang-zju** [comment]
> I raised a PR for task `update charts/index.yaml`: #5579

updated

**Comment by zhzhuang-zju** [comment]
king ping @Nishant-k-sagar 
Have you made any progress recently? Or let me know which tasks you're interested in, and I can assign them to you.

**Comment by MAVRICK-1** [comment]
@zhzhuang-zju if no one is working on this issue, Can I work on it

**Comment by zhzhuang-zju** [comment]
sure, let me know which tasks you're interested in, and I can assign them to you.

**Comment by MAVRICK-1** [comment]
@zhzhuang-zju thanks, I want take up the remaining issues.
- update hack/scan-image-vuln.sh
- update sample file of karmada operator
- update CHANGELOGS.md

**Comment by zhzhuang-zju** [comment]
assigned~

**Comment by MAVRICK-1** [comment]
Small question, should I have make a separate PR for each  issue?

**Comment by zhzhuang-zju** [comment]
@MAVRICK-1  yes, I believe so

**Comment by zhzhuang-zju** [comment]
@MAVRICK-1  yes, I believe so

**Comment by RainbowMango** [comment]
/close
as all tasks are finished.
