### ISSUE TITLE
[Umbrella] Remove deprecated address and port parameters

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#5547]
since we deprecated `--bind-address` and `secure-port` in some components, we're going to remove them in the release v1.12.

- [x] karmada-agent: @whitewindmills https://github.com/karmada-io/karmada/pull/5548
- [x] karmada-controller-manager: @whitewindmills https://github.com/karmada-io/karmada/pull/5549
- [x] karmada-descheduler: @chaosi-zju https://github.com/karmada-io/karmada/pull/5552
- [x] karmada-scheduler: @chaosi-zju https://github.com/karmada-io/karmada/pull/5551
- [x] karmada-scheduler-estimator: @seanlaii https://github.com/karmada-io/karmada/pull/5555

/help

Ref: https://github.com/karmada-io/karmada/issues/5219

**Comment by whitewindmills** [comment]
> how about assign karmada-scheduler and karmada-descheduler to me?

welcome
/assign @chaosi-zju

**Comment by seanlaii** [comment]
If possible, I would like to pick up karmada-scheduler-estimator. Thank you!

**Comment by seanlaii** [comment]
Is there any change that we have to make for `karmada-operator`? Looks like it has been already cleaned.

**Comment by whitewindmills** [comment]
@seanlaii thanks for your remainder.

**Comment by RainbowMango** [comment]
/close
All tasks are done. Thank you to everyone who contributed to this task. @whitewindmills @chaosi-zju @seanlaii
