### ISSUE TITLE
[Umbrella] Defining resource deleteion policy to support migration rollback

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#5577]
**What would you like to be added**:

Provides the ability to roll back migration safely. 

**Why is this needed**:

For specific details, please refer to #5101.

The specific work items can be planned as follows:

- [x] New proposal @CharlesQQ @XiShanYongYe-Chang #5101
- [x] Proposing API to support migration rollback @RainbowMango #5575 
- [x] Function Implementation @a7i #5597 
- [x] Refactor: optimize the processing of labels and annotations during resource depletion @a7i #5747
- [x] Rollback the migration of dependency distributed resources @XiShanYongYe-Chang #5717 
- [x] karmadactl promote can help rollout safely @wulemao #5601
- [x] Test Coverage 
  - [x] UT @a7i #5597 
  - [x] E2E @wulemao #5609
- [x] Document Description @wulemao https://github.com/karmada-io/website/pull/698 https://github.com/karmada-io/website/pull/697

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i would you like to contribute this feature?
cc @a7i

**Comment by a7i** [comment]
> Hi @a7i would you like to contribute this feature? cc @a7i

Yes absolutely! 🎉

**Comment by wulemao** [comment]
Hi, everybody, I am working on #5380 tasks, which is highly relevant to this issue.

I am interested in this issue too, could you please assign some related test job to me?

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i, how about handing over E2E tasks to @wulemao?

**Comment by RainbowMango** [comment]
I added one more task, which we should let `karmadactl promote` leverage this feature to guarantee the promotion can be rolled back safely.  To address the issue #3004 sent by @chaunceyjiang .

**Comment by wulemao** [comment]
> I added one more task, which we should let `karmadactl promote` leverage this feature to guarantee the promotion can be rolled back safely. To address the issue #3004 sent by @chaunceyjiang .

It is also a very interesting optimization. could I assign for it?

**Comment by XiShanYongYe-Chang** [comment]
Thanks all~
/close
