### ISSUE TITLE
[Summer OSPP 2024] Karmada supports the OverridePolicy dynamic configuration mechanism.

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#5608]
**What would you like to be added**:
Karmada utilizes the Kubernetes native API and provides advanced scheduling capabilities. When scheduling cloud-native applications to different member clusters, users may need to configure some differences for the various member clusters, such as setting different environment variables or images for different member clusters. To address this, Karmada provides a differentiated configuration policy API - OverridePolicy, which can set some differentiated configuration information for different clusters.

Currently, the use of OverridePolicy has a limitation - it can only set some static values and cannot dynamically set values based on certain conditions. This limitation restricts the usage scenarios of OverridePolicy. Therefore, we hope to provide a mechanism that can dynamically set values based on conditions. This will enhance the flexibility of using OverridePolicy for cluster differentiation configuration and bring more extensibility to users. For example, users can extend OverridePolicy by defining CEL or Lua languages, and the community has already tracked related issues to push forward with a specific solution.

See #4739 #4799

As we discussed at the community meeting(2024-08-27), we agree to postpone this feature for a while until there is more evidence showing that this is a common requirement.

So we decided to first implement the more common requirements. See #5330

Project link: https://summer-ospp.ac.cn/org/prodetail/245c40337

Parts of: https://github.com/karmada-io/karmada/issues/4879

Desired outcomes:

- [x] Proposal #5449
- [x] API #5581
- [x] Implementation  #5591
- [x] UT of this feature #5591
- [x] e2e of this feature #5591
- [x] website of user-guide https://github.com/karmada-io/website/pull/693
- [x] More validation as discussed at https://github.com/karmada-io/karmada/pull/5591#discussion_r1794603622. #5671

**Comment by RainbowMango** [comment]
/close
All tasks done. Great thanks to @sophiefeifeifeiya @chaunceyjiang
