### ISSUE TITLE
[Feature] Expose APIServer Service provisioned by karmada-operator 

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#5767]
**Background**
Currently, there is no reliable method to reference the Service for the Karmada APIServer. Users have to infer the Service based on internal implementation details, which can change over time, making this approach fragile and unreliable. This feature aims to provide a robust and stable way to expose Karmada services, particularly the APIServer, to external clusters or networks.

**Proposal**
https://github.com/karmada-io/karmada/pull/5599

The goal of this feature is to enhance the karmada-operator to include the Karmada API Server Service information in the status of Karmada resource objects. This will provide a standardized and reliable way for third-party applications to discover and interact with the Karmada API Server Service. The feature will ensure that the service information is consistently available and up-to-date, regardless of internal implementation changes.

**Iteration Tasks**
- [x] Feature proposal. (@jabellard, #5599)
- [x] Restrict the supported [ServiceType](https://github.com/karmada-io/karmada/blob/057cf860f41afc60f7505196c6df5979a2642068/operator/pkg/apis/operator/v1alpha1/type.go#L280-L283) by adding some validations. (@RainbowMango, #5769)
- [x] Enable Service type : `LoadBalancer`. (@chaosi-zju, #5773)
  * The [runUploadAdminKubeconfig()](https://github.com/karmada-io/karmada/blob/adef1e59748e1e1d31cb75fffe406b5dd69a66d7/operator/pkg/tasks/init/upload.go#L62-L114) didn't handle service with type `LoadBalancer`.
- [x] Feature implementation
  - [x] Code (@jabellard, https://github.com/karmada-io/karmada/pull/5775)
  - [x] Test (@jabellard, https://github.com/karmada-io/karmada/pull/5775)
  - [x] Documentation (@RainbowMango, #6015)
    * We should have a doc to introduce how to access the karmada-apiserver, like [Access The Argo CD API Server](https://argo-cd.readthedocs.io/en/stable/getting_started/#3-access-the-argo-cd-api-server)

**Comment by RainbowMango** [comment]
@jabellard @chaosi-zju What do you think of having a doc for this feature?
Let me know if you are going to help with it.

**Comment by jabellard** [comment]
> @jabellard @chaosi-zju What do you think of having a doc for this feature? Let me know if you are going to help with it.

@RainbowMango , @chaosi-zju : Thanks for tackling the other items in this epic. I can do this last one. Today, we have some docs for the operator, so I'm thinking I can just add to it by adding instructions for discovering the API Server service for a Karmada instance. What do you think?

**Comment by RainbowMango** [comment]
Yes, I agree, users need the instructions for exporting APIServer.

For now, I think we can put the document at the [operator README](https://github.com/karmada-io/karmada/blob/master/operator/README.md). For the long term, I guess we should move it to the website as we are going to have more documents.

**Comment by RainbowMango** [comment]
@jabellard Any update?

**Comment by jabellard** [comment]
> @jabellard Any update?

@RainbowMango , thanks for the reminder. I lost track of this umbrella issue at some point. Just submitted a [PR](https://github.com/karmada-io/karmada/pull/5886) for enhancing the docs.
