### ISSUE TITLE
[Umbrella] Bump Kubernetes dependency from v1.30.2 to v1.31.2

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#5796]
This issue is used to track Kubernetes dependency update tasks.

- [x] Bump Kubernetes dependency from v1.30.2 to v1.31.2  (@RainbowMango, #5807)
- [x] Bump [sigs.k8s.io/controller-tools/cmd/controller-gen](https://github.com/karmada-io/karmada/blob/ec3f9cfd8f9b6be245cd14bdd5f872ef39826500/hack/update-crdgen.sh#L22) to [v0.16.5](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.16.5). (@RainbowMango, #5808)
- [x] Bump [sigs.k8s.io/controller-runtime](https://github.com/karmada-io/karmada/blob/20bfceb37d45437dac42ebae171cc6dbcac38dfb/go.mod#L57) from v0.18.4 to [v0.19.1](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.19.1) (@RainbowMango, #5807)
- [x] Bump `sigs.k8s.io/custom-metrics-apiserver` to v1.31.x 
  - [x] Use `v1.30.1-0.20241105195130-84dc8cfe2555` pseudo version before official release. (@RainbowMango, #5807)
- [x] Bump [Golang](https://github.com/karmada-io/karmada/blob/20bfceb37d45437dac42ebae171cc6dbcac38dfb/go.mod#L3) from v1.22.7 to v1.22.9. (@RainbowMango, #5820)

**Prerequisites**
- [x] Ensure controller names are unique when emitting metrics. (@chaosi-zju, #5799)
- [x] https://github.com/karmada-io/karmada/pull/5804

**Follow Up**
Things should be cleaned up after the dependency bump.
- [x] Bump [sigs.k8s.io/custom-metrics-apiserver](https://github.com/kubernetes-sigs/custom-metrics-apiserver) to v1.30.1-0.20241105195130-84dc8cfe2555
  * After v1.31.0 gets released, we then update to that official version.
- [x] Bump [sigs.k8s.io/metrics-server](https://github.com/kubernetes-sigs/metrics-server) to v0.7.1-0.20240906155142-bb44be145648
  * The ideal version is v0.8.0 (Waiting for https://github.com/kubernetes-sigs/metrics-server/issues/1565)
  * But we can't update metrics-server as it bumps Go to v1.23, [which is incompatible with Kubernetes v1.31](https://github.com/kubernetes-sigs/metrics-server/issues/1565#issuecomment-2500037056). 
- [x] Removed deprecated `workqueue.RateLimiter` to get CI happy. (#5835)
  * Generic AsyncWork to remove reference to deprecated functions.
- [x] Enable deprecation check (@seanlaii, https://github.com/karmada-io/karmada/pull/5861)
- [x] Replace `grpc.DialContext` and `grpc.DialContext` as [mentioned in the discussion](https://github.com/karmada-io/karmada/pull/5861#discussion_r1857551645). (@seanlaii, #6026)
- [x] Complete the missing documentation bout controller lists. (@chaosi-zju, https://github.com/karmada-io/website/pull/733)
- [x] Explore the failing unit tests found at [this pr](https://github.com/karmada-io/karmada/pull/5820#issuecomment-2477895297). (@XiShanYongYe-Chang, https://github.com/karmada-io/karmada/pull/5846)

References:
- For swagger changes: https://github.com/kubernetes/kubernetes/pull/122891
- For karmada-search changes: https://github.com/kubernetes/kubernetes/pull/125483

**Comment by RainbowMango** [comment]
@seanlaii Thank you for reaching out and expressing your interest in contributing to the project. 

I [disabled the deprecation check](https://github.com/karmada-io/karmada/blob/fc1df776dcd3a8ca6a8f5507d90743471ccd066f/.golangci.yml#L85-L88) in the previous PR to keep the PR at an appropriate size for review. Now it's time to enable this check and fix the deprecation warnings accordingly. 
Please let me know if you are interested in this.

**Comment by seanlaii** [comment]
Hi @RainbowMango , thanks for the info! 
Yes, I am interested in this. 
Do I need to wait for these [sigs.k8s.io/custom-metrics-apiserver](https://github.com/kubernetes-sigs/custom-metrics-apiserver) and [sigs.k8s.io/metrics-server](https://github.com/kubernetes-sigs/metrics-server) to be completed?

**Comment by RainbowMango** [comment]
Thanks.
> Do I need to wait for [sigs.k8s.io/custom-metrics-apiserver](https://github.com/kubernetes-sigs/custom-metrics-apiserver) and [sigs.k8s.io/metrics-server](https://github.com/kubernetes-sigs/metrics-server) to be completed?

No. All you need to do is remove the following line:
https://github.com/karmada-io/karmada/blob/fc1df776dcd3a8ca6a8f5507d90743471ccd066f/.golangci.yml#L85-L88
And then get the warnings by running the following command:
```
hack/verify-staticcheck.sh
```

**Comment by RainbowMango** [comment]
/close
as all tasks done. Thanks to everyone who contributed to this~
