### ISSUE TITLE
Integration karmadactl register to ci for registering PULL mode clusters

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#5916]
**What would you like to be added**:
In release1.12, we have overhauled the `karmadactl register` command to minimize the permissions required for Pull mode clusters to access Karmada control plane resources. To support this feature and test it within CI, I aim to integrate `karmadactl register` into our CI pipeline, replacing the [deploy-karmada-agent.sh](https://github.com/karmada-io/karmada/blob/master/hack/deploy-karmada-agent.sh).

Prerequisites:
- [ ] remove the unnecessary file localization steps when karmadactl register. (@zhzhuang-zju #5862)

Based on the installation method, they can be divided into:
- karmadactl init
- [ ] Integration `karmadactl register` to ci [CLI](https://github.com/karmada-io/karmada/blob/master/.github/workflows/installation-cli.yaml) for registering PULL mode clusters
- helm
- [ ] Integration `karmadactl register` to ci [Chart](https://github.com/karmada-io/karmada/blob/master/.github/workflows/installation-cli.yaml) for registering PULL mode clusters
- operator
- [ ] Support Karmada installed by karmada-operator to use karmadactl register (@zhzhuang-zju #5755)
- [ ] Integration `karmadactl register` to ci [Operator](https://github.com/karmada-io/karmada/blob/master/.github/workflows/installation-cli.yaml) for registering PULL mode clusters
- local-up
- [ ] Integration `karmadactl register` to ci [CI Workflow](https://github.com/karmada-io/karmada/blob/master/.github/workflows/installation-cli.yaml) for registering PULL mode clusters (@zhzhuang-zju #5763)

Extra：
- [ ] remove [deploy-karmada-agent.sh](https://github.com/karmada-io/karmada/blob/master/hack/deploy-karmada-agent.sh) as it amplifies the Pull mode cluster's permission to access control plane resources.

**Why is this needed**:

**Comment by SkySingh04** [comment]
Hey @zhzhuang-zju , is this issue available to be taken up? Would love to work on this!

**Comment by zhzhuang-zju** [comment]
@SkySingh04 Of course, you can choose the tasks you're interested in and I'll assign them to you. However, these tasks may require pre-work #5862 to be merged in first before they can be carried out

**Comment by SkySingh04** [comment]
@zhzhuang-zju Awaiting your review on this!

**Comment by zhzhuang-zju** [comment]
> [@zhzhuang-zju](https://github.com/zhzhuang-zju) Awaiting your review on this!

@SkySingh04 Sorry for the delay, I leave some comments in the corresponding PR
