### ISSUE TITLE
[bugfix] workqueue metrics are mising

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#5954]
**What happened**:
We received reports that the controller's work queue metrics can not be emitted. (See [#5945](https://github.com/karmada-io/karmada/issues/5696) for more details, thanks to @CharlesQQ for reporting this).

This issue occurred before and was fixed in release 1.0 in [#945](https://github.com/karmada-io/karmada/pull/945), and then we made some subsequent impairments in [#2899](https://github.com/karmada-io/karmada/pull/2899) and [#3012]((https://github.com/karmada-io/karmada/pull/3012)). (Thanks to @Garrybest for doing this)

However after [#2998](https://github.com/karmada-io/karmada/pull/2998) and [#4706](https://github.com/karmada-io/karmada/pull/4706), this issue was introduced again in release-1.10.

This issue is used to track any relevant fix to ensure the problem is fully resolved without introducing any potential risk.

**Root Cause**:
From Go 1.21, the program initialization order was changed, and the metrics from the controller-runtime missed the chance of registration.

**Iteration tasks**:
- [x] Revist [#2998](https://github.com/karmada-io/karmada/pull/2998), fix potential risk or twist solutions.
- [x] Clarify the usage of [Service Reference](https://github.com/karmada-io/karmada/blob/c2de90bb5e3df29ecaebf28509c4fa0e7887043e/vendor/k8s.io/api/admissionregistration/v1/types.go#L1174-L1180) in the [ResourceInterpreterWebhookConfiguration](https://github.com/karmada-io/karmada/blob/5b48832496aaf7d39d7619412da954b04fcb6c8a/pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go#L43-L50) API. (#6109, @RainbowMango)
- [x] Clarify the usage documentation of `Service Reference` in the `ResourceInterpreterWebhookConfiguration`. ([#5969](https://github.com/karmada-io/karmada/pull/5969), @XiShanYongYe-Chang)
- [x] Minimum fix on master.  (#5972, @XiShanYongYe-Chang )
- [x] Backport to release branches. (release-1.10~release-1.12)  (#5979)
- [x] Cleanup workaround made on release-1.0. (#5945, @chaosi-zju)
- [x] Introduce tests to cover the metrics. (#6003, @chaosi-zju)
- [x] Expose metrics of `karmada-metrics-adapter`. (#6013, @chaosi-zju)

**Other Potential risks**
- [x] `karmada-webhook` panic in case of invalid configuration. ([#5960](https://github.com/karmada-io/karmada/pull/5960), @XiShanYongYe-Chang)
- [x] #5958

**References**:
- From Go 1.21, the program initialization order was specified more precisely. See [Go 1.21 release notes](https://tip.golang.org/doc/go1.21) for more details.

Echo from the release notes:
> Package initialization order is now specified more precisely. The new algorithm is:
> * Sort all packages by import path.
> * Repeat until the list of packages is empty:
>    - Find the first package in the list for which all imports are already initialized.
>    - Initialize that package and remove it from the list.

- [Go Program initialization](https://go.dev/ref/spec#Program_initialization)
- Issue in controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/issues/1969
- Issue in Kubernetes: https://github.com/kubernetes/kubernetes/issues/128326

**Comment by RainbowMango** [comment]
Got it.

**Comment by RainbowMango** [comment]
> The actual situation is that these custom metrics are not available right after installing the two components (not even zero values).
They can only be viewed once actually resources are scheduled.

Just a guess, this is due to the metrics needing some labels to be initiated. Like `result` and `type` in [estimating_request_total](https://github.com/karmada-io/karmada/blob/be674c7382a591d4eea8bba032dd334be4af0ca1/pkg/estimator/server/metrics/metrics.go#L52-L57). 

Show an example of the metrics?

**Comment by RainbowMango** [comment]
Thanks. That's the reason.

**Comment by stulzq** [comment]
v1.9.0 can not find metric `workqueue_adds_total`

**Comment by XiShanYongYe-Chang** [comment]
Hi @stulzq, thanks for your feedback~

**Comment by chaosi-zju** [comment]
> v1.9.0 can not find metric `workqueue_adds_total`

Hi @stulzq , from previous investigation:
    In `Karmada v1.9.9`, we still use `go v1.20`, the Karmada controller didn't miss workqueue metrics.
    From `Karmada v1.10.0`, we use `go v1.21`, start introducing this problem, metrics missed.

Can you please how you installed karmada?

**Comment by chaosi-zju** [comment]
> v1.9.0 can not find metric `workqueue_adds_total`

There is another situation, if you use `karmada v1.9.0`, but your go version is `go v1.21` or higher, you will also have problems.

**Comment by RainbowMango** [comment]
/unassign @husnialhamdani 
/close
Thanks again to @CharlesQQ for reporting this issue.
