### ISSUE TITLE
KEP-521: Scheduler Estimator TODO List

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#617]
The PR #580 has given a new proposal about adding Cluster Accurate Replica Estimator for scheduler decision reference. Here is the TODO List about the proposal.

- [x] API: field movement
Move `ReplicaResourceRequirements` and `Replicas` into `ResourceBindingSpec`. #637
- [x] API: field addition
Replace `ReplicaResourceRequirements` by `ReplicaRequirements`. #657
- [x] pb: code generate script. #638
- [x] pb: proto struct definition. #638
- [x] replica estimator server: new module #700
- [x] replica estimator client: adapting scheduler for gRPC calling #721
- [x] deploy: deploy script #742 #764 
- [x] test: more test cases #718
- [x] docs: README #765 
- [x] helm: support helm install #771

**Comment by RainbowMango** [comment]
Thanks for your work!
I wonder if we can finish this work by next week? (We might cut a release next week, and I really want this feature could be completely included in it.)

**Comment by RainbowMango** [comment]
> helm: support helm install

**Comment by Garrybest** [comment]
> Any idea about the chart part?

Well, I am not familiar with helm. Still need help. The other work could be done before next week.

**Comment by RainbowMango** [comment]
Fine. Let's ask @jrkeen @algebra2k for help.

`karmada-scheduler-estimator` is an `optional` components which intends to be installed to `host cluster` along with `karmada-scheduler`. And here is the [karmada-scheduler-estimator.yaml](https://github.com/karmada-io/karmada/blob/master/artifacts/deploy/karmada-scheduler-estimator.yaml).

Any idea?

**Comment by jrkeen** [comment]
> Fine. Let's ask @jrkeen @algebra2k for help.
> 
> `karmada-scheduler-estimator` is an `optional` components which intends to be installed to `host cluster` along with `karmada-scheduler`. And here is the [karmada-scheduler-estimator.yaml](https://github.com/karmada-io/karmada/blob/master/artifacts/deploy/karmada-scheduler-estimator.yaml).
> 
> Any idea?

I will do this next week.

**Comment by Garrybest** [comment]
Glad to hear that🚀, thanks @jrkeen.

**Comment by RainbowMango** [comment]
Congrats! Thanks for @Garrybest 's excellent work, that means a lot to the community.

**Comment by Garrybest** [comment]
You'are welcome. It's my pleasure. @RainbowMango
