### ISSUE TITLE
support for karmada TODO list installed by helm

### ISSUE THREAD

**Issue by algebra2k** [karmada-io/karmada#652]
We discussed the matter of karmada helm installation at the weekly meeting on 2021-08-17, for which we have already worked on this part, and here is the TODO about this work:

- [x] helm pre-hook job
- [x] make templates to compatible currently version crds
- [x] make karmada-apiserver component template
- [x] make karmda-scheduler component template
- [x] make karamda-controller-manager component template
- [x] make kube-controller-manager component template
- [x] make kube-webhook component template
- [x] make karmada-agent component template 
- [x] helm post-hook job
- [x] add helm tests
- [x] support etcd installation
- [x] complete document

**Comment by RainbowMango** [comment]
Seems all tasks have been done at #668?

**Comment by algebra2k** [comment]
> Seems all tasks have been done at #668?

Yes, The issue all done.

**Comment by RainbowMango** [comment]
OK, dude, let's 
/close
it.
